<?php

use Illuminate\Database\Seeder;

class BeschouwingfunctiesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('beschouwingfuncties')->delete();

        $beschouwingfuncties = [
            [
                'title' => 'Beschouwing op Informatievoorziening',
                'body' => '<p>Er blijkt geen blauwdruk te zijn voor de vormgeving van de informatievoorziening. Het aanbod aan informatie is onbegrensd. De ondersteunende instellingen worden geconfronteerd met een grote diversiteit aan doelgroepen die elk hun eigen informatiebehoeften hebben. Zij vinden het vaak erg lastig hun informatiebehoefte scherp te articuleren. Er zijn grote verschillen in behoeften en informatieaanbod tussen en binnen de diverse deelsectoren van de cultuursector. Ten aanzien van het aanbod is het grootste verschil of er ondersteunend kennisinstituut aanwezig is in een bepaalde deelsector, of dat informatie uit veel verschillende bronnen moet worden verzameld.</p>
<p>De informatie die beschikbaar is, blijkt vaak niet goed geordend en is daarmee slecht toegankelijk. Het veld vermoedt dat de ondersteunende instellingen veel informatie hebben, maar wat ze hebben is vaak onbekend en mede daardoor niet goed vindbaar.</p>
<p>In een wereld waarin informatie overvloedig beschikbaar is, neemt de behoefte aan duiding van informatie toe. Duiding moet er voor zorgen dat trends en ontwikkelingen adequaat en tijdig worden vertaald naar bruikbare informatie voor beleid en de praktijk van culturele instellingen en overheden.</p>
<p>De ondersteunende instellingen zoeken naar hun rol als duider van informatie. Over het algemeen zijn ze hier terughoudend in. Het ambitieniveau zou hoger kunnen. De ondersteunende instellingen zouden zich meer als autoriteit (&ldquo;kwaliteitskeurmerk&rdquo;) op het gebied van informatievoorziening kunnen manifesteren.</p>
<p>Er zijn ons geen opvallend goede voorbeelden bekend van ondersteunende instellingen in andere sectoren die de functie informatievoorziening zeer goed op orde hebben en als voorbeeld kunnen dienen voor de cultuursector. Onze ervaring is dat er altijd een kloof bestaat en zal bestaan tussen de informatie die beschikbaar is en de informatie die gewenst is.</p>
<p>We hebben bezien hoe informatievoorziening in het aanpalende domein onderwijs is georganiseerd. In informatievoorziening spelen in het onderwijs de brancheorganisaties zoals de po-, vo-, en mbo-raad, en voor het hoger onderwijs de Vereniging Hogescholen (VH) en de Vereniging Samenwerkende Nederlandse Universiteiten (VSNU) de voornaamste rol. Hun websites zijn een bron van informatie omtrent allerlei verschillende (actuele) thema&rsquo;s en er worden publicaties, onderzoeken, feiten en cijfers van de sector en nieuwsberichten gedeeld. Daarnaast kan het veld ook bijvoorbeeld informatie vinden over wetgeving en wat dit betekent voor de onderwijsinstellingen. Deze organisaties zijn wel specifiek belangenbehartigers, waardoor zij afwijken van de positie van de ondersteunende instellingen in de cultuursector.</p>
<p>Een partij in de onderwijssector die qua positie te vergelijken is met een ondersteunende instelling in de cultuursector, is Kennisnet. Kennisnet ondersteunt scholen specifiek met ICT en doet dit onder andere door het geven van strategisch advies en het aanbieden van expertise. Wanneer het gaat om informatievoorziening op het gebied van onderwijs en ICT is Kennisnet een grote bron van informatie voor het veld, waarbij hun website een schat aan informatie bevat over allerlei thema&rsquo;s, ontwikkelingen op het gebied van ICT-ontwikkeling in het onderwijs, nieuwe trends en inzichten, rapporten en brochures. Bij Kennisnet werken meer dan 75 fte medewerkers. Het onderwijs is een veel grotere maar relatief minder diverse sector dan de cultuursector.</p>',
                'functie_id' => '1'
            ],
            [
                'title' => 'Onderzoek &amp; Ontwikkeling',
                'body' => '<p>De cultuursector heeft geen onderzoeksinstituut dat voor de gehele sector onderzoek doet naar bijvoorbeeld de effectiviteit van beleid. Elke ondersteunende instelling besteedt in meer of mindere mate (afhankelijk van beschikbare formatie en kennis die nogal eens beperkt zijn) aandacht aan de functie onderzoek. Andere sectoren zoals zorg (o.a. Trimbos-instituut, Nivel), sport (o.a. NOC*NSF en Kenniscentrum Sport), mobiliteit (o.a. Kennisinstituut Mobiliteitsbeleid) en wetenschap (o.a. NWO en Rathenau) hebben onderzoeksinstituten en kenniscentra die kennis leveren voor hun sector. Ze verrichten hiervoor eigen onderzoek of laten onderzoek doen en verzamelen elders ontwikkelde kennis. Deze instituten zorgen ervoor dat overheden en organisaties beleid kunnen ontwikkelen met een stevig kennisfundament. Dat doen ze door het analyseren en verklaren van ontwikkelingen, het opstellen van verkenningen en scenario&rsquo;s en het analyseren van de effecten van beleidsinstrumenten. Voor de cultuursector als geheel doet alleen de Boekmanstichting dit, maar, mede door de beperkte capaciteit, in beperkte mate. Veel partijen in de diverse deelsectoren hebben wel behoefte aan gespecialiseerde onderzoekers.</p>
<p>De vraag is of de gehele cultuursector een eigen kennisinstituut nodig heeft. Organisaties als het Sociaal en Cultureel Planbureau en het CBS zouden wellicht meer kunnen betekenen voor de cultuursector. Dit kan alleen als de sector in staat is zijn informatiebehoeften goed te formuleren, er bovendien een opdracht inclusief financiering wordt gegeven en ten slotte de expertise daar aanwezig is of in huis kan worden gehaald. Daarin is vermoedelijk nog veel te verbeteren. De rol van het ministerie van OCW moet in dit verband nadrukkelijk worden genoemd. Het ministerie heeft de afgelopen jaren vele onderzoeken uitgevoerd of laten doen (door o.a. commerci&euml;le onderzoeksbureaus en universiteiten) waarvan de uitkomsten bruikbaar zijn voor de beleidsontwikkeling voor diverse thema&rsquo;s in de cultuursector (o.a. Cultuur in Beeld, Database subsidies). Deze onderzoeken worden door de sector gewaardeerd maar er worden vraagtekens gezet bij de continu&iuml;teit van de onderzoeken (volgen van ontwikkelingen en duiden van verschillen). Ook wordt een sector brede onderzoeksagenda/programma gemist.</p>
<p>Naast het voornamelijk kwantitatieve onderzoek is er behoefte aan meer kwalitatief en reflectief onderzoek. Wat zijn de maatschappelijke en economische waarde en betekenis van de bijvoorbeeld podiumkunsten en de beeldende kunst? Antwoorden op dit soort vragen zijn nodig om je als sector te kunnen ontwikkelen. Maar het zal altijd een zoektocht blijven hoe de via onderzoek gegenereerde kennis en inzichten het best kunnen worden omgezet naar interventies in de praktijk.</p>',
                'functie_id' => '2'
            ],
            [
                'title' => 'Beheer &amp; Ontsluiting',
                'body' => '<p>Voor de functie beheer &amp; ontsluiting is er geen eenduidig beeld voor de verschillende deelsectoren. Het gaat hier om de zorg voor en toegankelijkheid van erfgoed, collecties en archieven die complete deelsectoren van de cultuur betreffen. Het is een brede taak, die naast de zorg voor beheer en behoud, ook de verantwoordelijkheid voor ontsluiting en beschikbaarstelling betreft, al dan niet digitaal, maar ook via fysieke presentaties en tentoonstellingen. Het contrast tussen de podiumkunsten waarin deze erfgoedtaak is vervallen en de sectoren film en creatieve industrie die hier met Eye en Het Nieuwe Instituut volwaardige en rijksgefinancierde erfgoedfuncties hebben, wordt door het veld schrijnend genoemd.</p>
<p>De verschillen tussen de diverse culturele deelsectoren in de collecties en het overig erfgoed zijn groot, en dat maakt dat de uitvoering van de erfgoedtaken sinds jaar en dag sterk verschilt per deelsector. Dat heeft onder meer te maken met het gegeven of het rijkscollecties betreffen en daarmee rijksverantwoordelijkheid is. Ook varieert de betekenis van de collecties, bijvoorbeeld in termen van de historische, museale en presentatiewaarde voor een groot publiek, naast de professionele betekenis en het collectieve geheugen van een sector.</p>
<p>In het algemeen is er echter sprake van zorg. We leven in een tijd die vanwege tal van ontwikkelingen (snelheid, meer volume) tot de minst gedocumenteerde dreigt te worden en dat geldt ook voor de cultuursector en zeker voor de creatieve industrie, denk aan het vastleggen van nieuwe media-uitingen of gaming. Wie bepaalt wat bewaard wordt? Voor archivering van overheidsinformatie bestaan verplichtingen op basis van de Archiefwet, maar dat geldt niet voor kunstuitingen. Er is dringend behoefte aan helderheid en beleid op dit punt, ook al om een helder antwoord te krijgen op de vraag welke collecties sectorbreed zijn en dus onderdeel van de ondersteuningsstructuur en welke collecties instellingsspecifiek zijn, en dus eigendom van de instelling. Dit vraagt echt om nader onderzoek om goed in kaart te brengen waar de knelpunten zitten en waar oplossingsrichtingen zijn te vinden.</p>
<p>Bepaalde ondersteuningsfuncties vallen niet onder de Wet op het Specifiek Cultuurbeleid (Wsc) maar onder andere wetgeving, in ieder geval in bepaalde deelsectoren. Zo geldt voor de bibliotheken de Bibliotheekwet en voor de erfgoedtaken is er de Erfgoedwet. Daarmee is voor bepaalde taken, zeker ten aanzien van collecties, de ondersteuning langjarig vastgelegd, waar dat in de Wsc telkens maar voor 4 jaar is.</p>
<p>In de podiumkunsten, zowel bij muziek als bij theater, ligt de grootste zorg (maar overigens niet de hoogste prioriteit qua ondersteuning) van het veld in het beheer, behoud en ontsluiting van de collecties. De afdeling Bijzondere Collecties van de Universiteit van Amsterdam heeft een deel van deze erfgoedcollecties van muziek en theater opgenomen. Hiervoor was tijdelijke financiering beschikbaar vanuit de erfenis van de voormalige sectorinstituten, maar de bodem van dat budget is in zicht. Collecties raken in het grotere geheel ondergesneeuwd en verweesd. Juist in deze tijd van digitalisering en toenemend (digitaal) mediagebruik en mede gezien de aandacht voor cultuureducatie, liggen er veel kansen in de grootschalige ontsluiting voor het brede publiek van muziek- en theatercollecties en producties. Beperkingen liggen in financiering en rechten. De cultuurproducerende instellingen hebben hier zelf ook baat bij maar nauwelijks gelegenheid toe.</p>
<p>Mogelijk ligt er een oplossing in een gedeelde verantwoordelijkheid met DEN, het kennisinstituut Digitale Cultuur, die ondersteuning biedt voor het gehele cultuur- en erfgoedveld op het gebied van digitale collectievorming en archivering. Een kerntaak van DEN is het stroomlijnen van digitale collectievorming en archivering van digitale cultuur. Hierbij heeft DEN ten doel de relatie tussen cultuurproducenten en erfgoedinstellingen op het gebied van de digitale collectievorming en archivering te versterken Het veld geeft aan behoefte te hebben aan praktische en technische ondersteuning. De collectiebeleidsrol zou dan mogelijk bij Het Nieuwe Instituut kunnen worden belegd. Het Nieuwe Instituut heeft immers een museum- en archieftaak voor het Museum voor Architectuur, Design en Digitale cultuur.</p>',
                'functie_id' => '3'
            ],
            [
                'title' => 'Vertegenwoordiging',
                'body' => '<p>De functie vertegenwoordiging valt in twee delen uiteen. In de eerste plaats wordt gedoeld op de representatie en zichtbaarheid: het vormen van een aanspreekpunt, het vervullen van de rol van boegbeeld namens de (deel)sector. In de tweede plaats gaat het om promotie van de gehele sector, vaak internationaal maar ook nationaal of regionaal in relatie tot andere culturele sectoren, zonder verlengstuk te zijn van het ministerie. In beide perspectieven gaat het om collectieve en objectieve belangenbehartiging en dus niet om de belangenbehartiging zoals brancheorganisaties zouden moeten doen. Een goed voorbeeld in de sportsector is de constructie van NOC*NSF: een organisatie met positie en gezag die een zichtbaar platform vormt voor de hele sector.</p>
<p>In de Beeldende Kunst heeft het Mondriaan Fonds een vertegenwoordigende positie, in ieder geval namens een deel van de sector. In de filmsector hebben EYE en het Filmfonds beide een vertegenwoordigende rol. Op het gebied van internationalisering is in de filmsector onduidelijk wie precies de regie heeft. In de podiumkunstensector heeft het Fonds Podiumkunsten, met het verdwijnen van MCN en TIN, amper deze rol over kunnen nemen en is deze sector daarmee ondervertegenwoordigd, ook als het gaat om internationalisering. Over het algemeen vraagt men zich overigens af in hoeverre van fondsen kan worden verwacht dat ze de gehele sector vertegenwoordigen, aangezien ze slechts een deel van de sector (kunnen) ondersteunen met financi&euml;le regelingen.</p>
<p>Verder overheerst het beeld dat er vooral sprake is van vele gespecialiseerde vertegenwoordigende kleinere partijen. Dit zijn meer belangenbehartigers dan vertegenwoordigers. Is dit erg of effectief? Gezien het belang van vertegenwoordiging is het de vraag of je niet meer in de ondersteuningsstructuur moet trekken, omdat al die kleine partijtjes zoveel meer moeite moeten doen om gehoord te worden. Daar waar samengewerkt wordt en er een nieuwe titel ontstaat (zoals de leescoalitie, het platform promotie cultuureducatie, of BKNL) is er sprake van meer volume: men vertegenwoordigt een groter deel van de sector. Ook weet men de belangen van de deelsector op die manier beter te vertegenwoordigen in de richting van bijvoorbeeld de politiek of het ministerie. De overheid heeft zelf ook behoefte aan vertegenwoordigende organen, en daarmee zou de sector er behoefte aan moeten hebben. Dat is de enige manier om als sector in contact te kunnen staan met de overheid. Met wie moeten zij anders spreken? Tegelijkertijd laat men zich in de culturele sector niet graag vertegenwoordigen en echte boegbeelden of organisaties die met gezag namens (deel)sectoren kunnen spreken zijn op de vingers van een hand of minder te tellen. Iedereen, groot of klein, waant zich uniek. Des te knapper van Kunsten &rsquo;92, de Akademie van Kunsten en de Federatie Cultuur dus dat zij zich als spreekbuizen met een (over het algemeen) eenduidig geluid weten te manifesteren.</p>',
                'functie_id' => '4'
            ],
            [
                'title' => 'Netwerkactivering',
                'body' => '<p>In deze functie staat het vormen, ondersteunen van en toegang verlenen tot netwerken binnen de deelsectoren en vooral ook met de omgeving centraal. Daarmee wordt de ontmoeting gefaciliteerd waardoor partijen elkaar binnen en buiten de sector leren kennen, kennis en informatie kunnen uitwisselen en eventueel tot nadere samenwerking kunnen komen. Er is ook een inhoudelijke en politiek-bestuurlijke kant aan netwerkactivering. Het zorgt er namelijk ook voor dat beleidsmatige kwesties aan de orde komen in debat en reflectie binnen en buiten de sector.</p>
<p>De taken in de ondersteuning bestaan daarbij onder meer uit inhoudelijke en praktische afstemming en co&ouml;rdinatie tussen de diverse partijen in en om de sectoren. Het gaat dan ook om (de organisatie van) bijeenkomsten, conferenties, studiedagen en lezingen. Netwerken, formeel en informeel, kunnen ook bestaan uit kenniskringen, community&rsquo;s en platforms, rond diverse thema&rsquo;s.</p>
<p>Er gebeurt veel op het gebied van netwerkactivering. Met het organiseren van allerlei soorten bijeenkomsten, wordt gelegenheid gecre&euml;erd voor intensivering van samenwerking en breder draagvlak. Hoe steviger de agenda is en hoe groter het belang dat deelnemers eraan hechten, des te effectiever het is. De mate van invulling van de netwerkfunctie hangt sterk samen drie factoren: 1) omvang en diversiteit van de sector (vergelijk bijvoorbeeld Letteren versus Cultuureducatie en cultuurparticipatie) 2) omvang en positie van ondersteunende instelling (vergelijk LKCA versus Boekmanstichting) en 3) de mate waarin de sector zichzelf organiseert of kan organiseren in kleine en grote netwerken. Vooral dat laatste valt in een aantal deelsectoren op. Daar waar &eacute;&eacute;n herkenbare partij die midden in het veld staat ontbreekt, ontstaan en groeien netwerken op eigen initiatief, daar waar een grote speler in de ondersteuningsstructuur is, is de sector vaak meer volgend, omdat die grote speler een goede voortrekkersrol kan spelen.</p>
<p>Met name de jaarlijkse grotere congressen die voor de hele (sub)sector worden georganiseerd, worden gewaardeerd als ondersteunende activiteit. Daarnaast heeft het veld, zeker als het gaat om internationalisering, behoefte aan inzicht en bruikbaarheid van netwerken, formeel en informeel. Voor de vertegenwoordiging van Nederland in het buitenland (zie ook functie vertegenwoordiging) ziet men het belang van participatie van ondersteunende instellingen in Europese en mondiale netwerken.</p>',
                'functie_id' => '5'
            ],
            [
                'title' => 'Beleidsondersteuning',
                'body' => '<p>De beleidsondersteuning in de cultuursector is een onderbelichte functie van de ondersteunende instellingen. Natuurlijk vormen de resultaten van onderzoek input voor nieuw beleid maar de ondersteunende instellingen stellen zich maar in zeer beperkte mate actief op als het gaat om het be&iuml;nvloeden en voeden van het beleid dat met name door het ministerie, provincies, gemeenten en fondsen wordt ontwikkeld en bepaald. Nationaal inhoudelijk cultuurbeleid werd in het verleden be&iuml;nvloed door de sectorinstituten. Deze rol lijkt nu vooral te liggen bij de brancheverenigingen (soms ook bij vakbonden), maar minder bij de ondersteunende instellingen.</p>
<p>In sommige andere sectoren zijn de beleidsondersteuning en uitvoering gekoppeld aan een financieringstaak. Voorbeelden hiervan zijn NOC*NSF in de sport en NWO in de wetenschap, hoewel in het laatste geval de nadruk in de huidige praktijk vooralsnog op financiering ligt.</p>
<p>Er zijn argumenten voor en tegen het onderbrengen van ondersteuning en financiering bij een enkele partij, anders dan de overheid zelf. Het cre&euml;ert in de regel daadkracht (beleid krijgt direct uitvoering), maar er ontstaat mogelijk een monopolistisch machtsblok. In de cultuursector is nog nauwelijks nagedacht over de meerwaarde en de risico&rsquo;s van een dergelijke bundeling van taken.</p>
<p>Een groot deel van het voor de cultuursector relevante overheidsbeleid ligt overigens niet bij OCW maar bij bijvoorbeeld SZW (arbeidsvoorwaarden en -omstandigheden), EZ (economische agenda), BuZa (EU-beleid), Justitie (vergunningen, auteursrechten) en vooral Financi&euml;n (begroting, fiscaliteit). Bijvoorbeeld de Geefwet en de btw-verhoging kunnen grote invloed hebben op de ontwikkeling van de economische positie van de cultuursector maar liggen niet op het bord van de minister van OCW. Dat maakt ook de beleidsondersteuning complex.</p>
<p>Het is wenselijk om bepaalde beleidsthema&rsquo;s die een meer tijdelijk karakter hebben maar wel bovensectorale aandacht verdienen bij een uitvoerende instelling te beleggen. Hieronder vallen dan ook opdrachttaken die de overheden willen uitbesteden. Opdrachttaken hangen samen met de verwezenlijking van specifieke beleidsthema&rsquo;s en beleidsdoelen van de overheden of de sector. Opdrachttaken zijn eindig en kennen daarom een tijdelijke ondersteuningsduur. Er ontstaat hiermee een opdrachtnemer-opdrachtgeversrelatie en urgentie en de vrijblijvendheid wordt gereduceerd. Voorbeelden zijn het ontwikkelen en implementeren van codes rond bepaalde thema&rsquo;s als diversiteit, governance en fair practice. Dergelijke opdrachttaken kunnen worden ondergebracht bij ondersteunende instellingen maar ook bij andere partijen, onder meer brancheverenigingen en commerci&euml;le onderzoeks- en adviesbureaus. Aandachtspunt hierbij is de mate waarin de verleende opdrachten worden uitbesteed dan wel aanbesteed aan gesubsidieerde, bekostigde of commercieel opererende partijen. Het opdrachtgeverschap van de overheden kent dan ook diverse vormen.</p>
<p>Een voorbeeld van deze aanpak die in de praktijk goed heeft gewerkt is het thema cultural governance. Cultuur+Ondernemen is aangewezen als &lsquo;eigenaar&rsquo; van dit thema en is trekker als het gaat om het ontwikkelen en toepassen van de kennis in de praktijk, waarbij de Code Governance Cultuur het inmiddels zeer breed bekende instrument is. Voor het thema Culturele Diversiteit, dat niet alleen op rijksniveau maar ook voor regionale en lokale schaal een grote rol speelt, is ook een code ontwikkeld en belegd bij de Federatie Cultuur, die voor de uitvoering van de werkzaamheden op het gebied van de Code Culturele Diversiteit wordt ondersteund door binoq atana. De uitvoering van het werk aan dit beleidsthema wordt mogelijk gemaakt met financi&euml;le steun van OCW, in de vorm van een opdrachttaak aan een werkgeversverband, niet aan een ondersteunende instelling. Het beleidsthema Fair Practice<em>, </em><em>een praktische uitwerking van de Arbeidsmarktagenda voor de culturele en creatieve sector, </em>wordt in opdracht van het ministerie van OCW door Kunsten&rsquo;92 uitgevoerd. Opdrachttaken laten uitvoeren door belangenbehartigers is kennelijk ook een manier om aandacht binnen en buiten de sector op een beleidsthema te vestigen. Zoals ook bij vertegenwoordiging is opgemerkt, is het van belang dergelijke taken te beleggen bij een partij die met autoriteit kan zeggen namens de gehele cultuursector &lsquo;eigenaar&rsquo; te zijn van het thema en namens het veld hierover kan spreken.</p>',
                'functie_id' => '6'
            ],
            [
                'title' => 'Deskundigheidsbevordering',
                'body' => '<p>Deskundigheidsbevordering is een belangrijke functie van ondersteunende instellingen, maar wordt niet in alle sectoren en voor alle bovensectorale onderwerpen als ondersteuningsfunctie aangeboden. De vari&euml;teit in de uitvoering is groot. Over het algemeen worden het aanbod en de kwaliteit van de aangeboden deskundigheidsbevordering door het veld gewaardeerd. Culturele instellingen kunnen voor deskundigheidsbevordering ook terecht bij brancheorganisaties, regionale ondersteunende instellingen en intermediairs evenals onderwijsinstellingen en trainingsbureaus, die in opleiden gespecialiseerd zijn.</p>
<p>Op het gebied van deskundigheidsbevordering wordt aangekaart vanuit het veld dat de samenwerking met het onderwijs gestimuleerd moet worden. Samenwerking met universiteiten en hbo&rsquo;s biedt op het gebied van deskundigheidsbevordering veel mogelijkheden. Voor deskundigheidsbevordering zou meer geld moeten komen, maar het veld vraagt zich af waar dit ondergebracht zou moeten worden: in een specifieke opleiding of bij instituten en brancheverenigingen? Een issue bij deskundigheidsbevordering vormt immers de kosten die in rekening worden gebracht bij de instellingen en/of de individuele deelnemers. Deze kosten worden door veel culturele instellingen al snel te hoog gevonden. Hierdoor bestaan er in de praktijk drempels die bevordering van de deskundigheid in de weg staan. Dit wordt door het veld als zeer ongewenst gezien.</p>
<p>Regelingen zoals Cultuureducatie met Kwaliteit bevatten deskundigheidsbevordering voor professionals ten aanzien van specialistische en didactische competenties. In de aanvragen die voor Cultuureducatie met Kwaliteit worden gedaan bij het Fonds voor Cultuurparticipatie, moet in principe aandacht worden besteed aan deskundigheidsbevordering. Een dergelijke voorwaarde zorgt dat er aandacht en middelen voor dit belangrijke onderwerp zijn.</p>
<p>Het Programma Ondernemerschap Cultuur (LinC, Wijzer Werven, ondersteuning aan middelgrote en kleine culturele instellingen) heeft de afgelopen jaren een belangrijke rol gespeeld bij de deskundigheidsbevordering in de sector. Veel professionals hebben opleidingen gevolgd die in het kader van het programma zijn aangeboden. De vraag is hoe na het aflopen van het programma het opleidingsaanbod, wellicht in afgeslankte, andere vorm, kan worden gecontinueerd. Want dat er behoefte aan is, staat buiten kijf.</p>
<p>De sector werkt nauwelijks met keurmerken, afgezien van BHV en diploma&rsquo;s in bepaalde technische of beveiligingsrollen. De certificering van interne cultuurco&ouml;rdinatoren (icc&rsquo;ers) door het LKCA is een echte uitzondering, die bovendien aan medewerkers in het onderwijs en niet aan medewerkers in de cultuursector ten goede komt. Er zit mede daardoor geen verplichtend karakter in bijscholing, en ook weinig richting of profilering in vereiste competenties. De positie van autoriteit en mogelijk zelfs toezichthouder is vanuit het instrument keurmerken niet belegd binnen de ondersteuningsstructuur. Die rol wordt overigens in de behoorlijk autonome en vrijgevochten culturele en creatieve sectoren ook niet gemist.</p>',
                'functie_id' => '7'
            ],
        ];

        DB::table('beschouwingfuncties')->insert($beschouwingfuncties);
    }
}
