<?php

use Illuminate\Database\Seeder;

class ToelichtingsectorsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('toelichtingsectors')->delete();

        $toelichtingsectors = [
            [
            	'title' => 'Podiumkunsten: Fonds Podiumkunsten',
            	'body' => '<p>De sector podiumkunsten is een brede en diverse sector met vele genres, die in toenemende mate in elkaar overlopen. Een deel van de professionele podiumkunsten is rijksgesubsidieerd, deels direct binnen de Basisinfrastructuur, deels via het Fonds Podiumkunsten (FPK). Ook andere overheden subsidi&euml;ren delen van het aanbod aan podiumkunsten, maar er is ook een grote en brede vrije sector die zonder subsidie opereert. De presentatieplekken voor de podiumkunsten, vooral concertzalen, schouwburgen en theaters, maar ook festivals, worden grotendeels lokaal gesubsidieerd, maar ook daar is een grote vrije sector van commerci&euml;le theaters en festivals. De ondersteuningsstructuur richt zich op het functioneren van de gehele sector podiumkunsten, met een focus op de professionele cultuurproducenten.</p>
<p>Tot 2013 bestonden er drie sectorinstituten, te weten Theater Instituut Nederland (TIN), Muziek Centrum Nederland (MCN) en het Nederlands Muziek Instituut (NMI). De sectorinstituten TIN en MCN zijn opgeheven als gevolg van de bezuinigingen in 2012. Ook de rijkssubsidie voor NMI is stopgezet, maar die instelling bestaat nog dankzij enige financiering van de gemeente Den Haag en intensieve samenwerking met onder meer het Haags Gemeentearchief. Een deel van de besteltaken en dus ondersteuningsfuncties is overgenomen door het Fonds Podiumkunsten, brancheverenigingen, zelfstandige stichtingen en andere instellingen zoals de Universiteit van Amsterdam, maar zonder structurele rijksfinanciering van deze taken. Andere taken zijn gestopt.</p>
<p>Wat er over is van de ondersteuningsstructuur voor de podiumkunsten wordt beschouwd als willekeurig en divergent. Regie, autoriteit en overzicht ontbreken. Een aantal spelers in het veld benoemt de ondersteuningsstructuur van de podiumkunsten zelfs als &lsquo;non-existent&rsquo;. Er leven grote zorgen over de verloren gegane expertise en het risico van verdwijnen van erfgoed, zoals de collecties die nu verweesd zijn. Ook wordt een centrale plek en een gedeeld wij-gevoel gemist. Andere spelers benoemen juist dat de inrichting van instituten automatisch tot bureaucratie leidt en dat hieraan ter beschikking gestelde middelen ten koste zouden gaan van budgetten voor producerende instellingen. Er wordt niet gepleit voor het in ere herstellen van de oude situatie, maar de gedachte overheerst dat de ondersteuningsstructuur sterk kan winnen aan toegevoegde waarde en toekomstbestendigheid.</p>',
            	'sector_id' => '1'
            ],
            [
            	'title' => 'Beeldende Kunst: Mondriaan Fonds',
            	'body' => '<p>De sector beeldende kunst is zeer divers en wordt gevormd door kunstenaars, kunstenaarsinitiatieven, presentatie-instellingen, galeries, musea, postacademische instellingen en festivals. Voor beeldende kunst heeft nooit een specifiek sectorinstituut bestaan met een aantal besteltaken c.q. ondersteuningsfuncties. Voor de sector beeldende kunst is, mede daarom, het Mondriaan Fonds vanuit de BIS-ondersteuning de aangewezen partij voor het invullen van een aantal van de ondersteuningsfuncties die anders geheel afwezig zouden zijn. Daarnaast vervullen veel spelers een eigen rol in de ondersteuning van de sector, zoals Platform BK, BKNL, Kunsten&rsquo;92, de Museumvereniging, Federatie Cultuur, de Kunstenbond, Dhaps, Binoq, Laps, KNAW, Boknet, ZaakNU, NGA en BBKnet.</p>
<p>In dit onderzoek ligt de nadruk op het Mondriaan Fonds en dan met name op de taken die niet direct te maken hebben met de financiering van beeldendekunstactiviteiten. Het Mondriaan Fonds bevordert bijzondere en vernieuwende projecten en activiteiten van beeldend kunstenaars, bemiddelaars (curatoren en critici), musea en andere erfgoedinstellingen, presentatie-instellingen, archieven, galeries en opdrachtgevers. Alle bijdragen hebben tot doel het stimuleren van de productie en de presentatie van relevante beeldende kunst en erfgoed uit Nederland in binnen- en buitenland op die plekken waar de markt dit (nog) niet doet.</p>
<p>Het Mondriaan Fonds is ontstaan uit een fusie van het Fonds BKVB en de Mondriaan Stichting. Sinds de fusie is er &eacute;&eacute;n loket voor individuele aanvragers en instellingen op het gebied van beeldende kunst en cultureel erfgoed. Het Mondriaan Fonds heeft jaarlijks zo&rsquo;n 26 miljoen euro te besteden. Het grootste deel van dit budget komt van het ministerie van OCW. Per jaar worden honderden projecten in Nederland en daarbuiten ondersteund. Daarnaast biedt het fonds stimuleringsprogramma&rsquo;s voor innovatie en promotie, die aanjagen en agenderen. Bij het Mondriaan Fonds werken 34 mensen. Bij de beoordeling van aanvragen wordt het fonds geadviseerd door 75 deskundigen.</p>',
            	'sector_id' => '2'
            ],
            [
            	'title' => 'Erfgoed: RKD en Mondriaan Fonds',
            	'body' => '<p>De landelijke ondersteuning in de culturele sector op het gebied van Erfgoed ligt bij het Nederlands Instituut voor Kunstgeschiedenis (hierna: RKD), en bij het Mondriaan Fonds, het publieke stimuleringsfonds voor beeldende kunst en cultureel erfgoed. Het gaat in dit onderzoek om erfgoed exclusief monumenten en archieven, met de nadruk op ondersteuning van musea.</p>
<p>Het RKD is een kennisinstituut met zowel een onderzoeksfunctie als een collectie- en publieksfunctie en heeft als kerntaak het verzamelen, beheren, beschikbaar stellen en presenteren van archief-, documentatie-, en bibliotheekmateriaal van en over de kunst van de Nederlanden in internationale context en het bevorderen van onderzoek hiernaar. De driehoek waarin het RKD opereert wordt gevormd door het publiek (fysiek en digitaal), de musea en de wetenschap. Met deze drie velden wordt veel samengewerkt. De organisatie bestond in eind 2016 uit 54 FTE.</p>
<p>Het Mondriaan Fonds bevordert bijzondere en vernieuwende projecten en activiteiten in beeldende kunst en erfgoed. Voor erfgoed kunnen musea en andere instellingen terecht bij het Mondriaan Fonds voor projectinvesteringen, opdrachten, programmering en bijdragen aan collecties.</p>
<p>Andere spelers in het veld van ondersteuning in de erfgoedsector zijn CODART, NICAS, ESNA, VNK, OSK, onderzoeksinstituten en universiteiten, DEN, DutchCulture, Rijksdienst voor Cultureel Erfgoed en individuele musea.</p>',
            	'sector_id' => '3'
            ],
            [
            	'title' => 'Film: EYE en Filmfonds',
            	'body' => '<p>In de ondersteuningsstructuur spelen het Filmfonds en EYE een belangrijke rol. Het Filmfonds heeft als primaire taak de financiering van de Nederlandse filmproducties en filmactiviteiten en als afgeleide taak ondersteuning met als beleidspijlers talentontwikkeling, innovatie, internationalisering en professionalisering. EYE is sinds 2010 onderdeel van de ondersteuningsstructuur en is een fusieorganisatie, ontstaan uit het Filmmuseum, Holland Film, het Nederlands Instituut voor Filmeducatie (NIF) en de Filmbank, waarvan niet alle taken zijn behouden wegens gelijktijdige bezuinigingen. De filmsector wordt op nationale schaal ook ondersteund door het Fonds voor Cultuurparticipatie, het Stimuleringsfonds Creatieve Industrie en nationaal opererende media-instituten zoals de NPO, Filmacademie en Instituut Beeld &amp; Geluid. Op internationale schaal is er ondersteuning door bijvoorbeeld Eurimage en Creative Europe Desk via DutchCulture. Regionaal en lokaal komt ook ondersteuning voor, onder meer provinciale en stedelijke film commissioners.</p>
<p>De filmsector is internationaal geori&euml;nteerd, wat betreft profilering, structuur en financiering. Net als filmfondsen in andere landen, voert het Filmfonds in directe samenhang met zijn centrale rol als financier een aantal ondersteunende functies uit, zoals internationale activiteiten, analyse en onderzoek en in het bijzonder de Netherlands Film Commission. Dat is het centrale aanspreek- en servicepunt voor producenten die in Nederland (delen van) hun productie willen uitvoeren en treedt op als de liaison tussen producenten en de bedrijven en professionals in de Nederlandse filmindustrie.&nbsp;</p>
<p>EYE is het Nederlandse filminstituut met primaire museale en erfgoedtaken en een aantal kennisgedreven ondersteuningsfuncties. In de ondersteuningsstructuur in sommige andere landen zijn kennis, educatie, promotie, collectie en financiering gecombineerd, terwijl dat in Nederland los is (EYE en Filmfonds). In sommige landen of regio&rsquo;s zoals Vlaanderen is bovendien de filmsector gecombineerd met televisie en andere audiovisuele sectoren zoals interactive media, waar dat in Nederland niet het geval is. Het Filmfonds pleit ervoor het filmbeleid ten minste te verbreden met het mediabeleid op rijksniveau, omdat enkel film te smal is geworden in dit huidige tijdperk waarin het publiek beeldcultuur veel breder consumeert dan enkel in de bioscoop.</p>
<p>De filmsector heeft een andere aard dan cultuursectoren waarin gesubsidieerde instellingen het meest toonaangevend zijn, omdat de globale filmsector over het algemeen en daarmee het grootste deel van wat in Nederland wordt vertoond aan films privaat georganiseerd en gefinancierd is. De Nederlandse filmproducties die wel worden gefinancierd moeten in dat speelveld opereren. In (bijvoorbeeld) de podiumkunsten is voor het artistieke aanbod de gehele keten (productie, distributie en exploitatie) ondersteund met publieke financiering, terwijl dat in de film veel beperkter is, eigenlijk alleen in bijzondere gevallen een deel van de productie en een deel van de presentatieplekken, zoals filmfestivals en lokale filmhuizen. Bioscopen hebben wel een verlaagd btw-tarief.</p>
<p>De zeven ondersteuningsfuncties die door Berenschot zijn onderscheiden, worden op nationale schaal uitgevoerd door het Filmfonds en EYE. Zij slagen hier over het algemeen redelijk goed in, maar de middelen zijn minder toereikend dan in het verleden. Zij hebben bovendien taken moeten opvangen die voorheen bij inmiddels opgeheven organisaties zoals het BINGER Filmlab en het Mediafonds waren belegd. Bij sommige ondersteuningsfuncties is de taakverdeling tussen het Filmfonds en EYE helder, zoals bij Beheer &amp; Ontsluiting. Bij de functies Vertegenwoordiging, Beleidsondersteuning en Deskundigheidsbevordering heerst echter onduidelijkheid en discussie, zoals ook al eerder door de Raad voor Cultuur werd geconstateerd, en het veld heeft daar last van.</p>',
            	'sector_id' => '4'
            ],
            [
            	'title' => 'Creatieve Industrie: Het Nieuwe Instituut en SFCI',
            	'body' => '<p>In de landelijke rijksgefinancierde ondersteuning zijn er twee partijen binnen de sector Creatieve Industrie die ondersteuning bieden aan het veld: Het Stimuleringsfonds Creatieve Industrie (SFCI) en Het Nieuwe Instituut.</p>
<p>Het Stimuleringsfonds Creatieve Industrie is het cultuurfonds voor architectuur, vormgeving, digitale cultuur en alle mogelijke crossovers daartussen. Het Stimuleringsfonds is in 2013 voortgekomen uit het voormalige Stimuleringsfonds voor Architectuur. Het Stimuleringsfonds kreeg een aantal taken overgeheveld van het Mondriaan Fonds op gebied van vormgeving. Ook kreeg het er een aantal nieuwe taken bij, zoals het stimuleren van de e-cultuur dat tot dan toe nog nergens was belegd. De taak van het Stimuleringsfonds is het ondersteunen van bijzondere en vernieuwende projecten en activiteiten van ontwerpers, makers en culturele instellingen in de creatieve industrie en het stimuleren van productie en presentatie van architectuur, vormgeving en digitale cultuur uit Nederland in binnenland &eacute;n buitenland. Via programma&rsquo;s en subsidies draagt het fonds bij aan het formuleren van ontwerpoplossingen voor maatschappelijke vraagstukken die breed gedragen zijn. Het Stimuleringsfonds heeft op dit moment 23 medewerkers in dienst.</p>
<p>Het Nieuwe Instituut is ontstaan op 1 januari 2013 uit een fusie van het Nederlands Architectuurinstituut, Premsela, Nederlands Instituut voor Design en Mode en Virtueel Platform, kennisinstituut voor e-cultuur. Het Nieuwe Instituut opereert in het werkveld creatieve industrie vanuit het Rijksarchief voor de Nederlandse Architectuur en Stedenbouw, het museum voor Architectuur, Design en Digitale Cultuur en het agentschap voor Architectuur, Design en Digitale Cultuur. Het Nieuwe Instituut is hiermee een ondersteunende instelling met sectorale taken. Het Nieuwe Instituut probeert met haar activiteiten de wisselwerking tussen architectuur, vormgeving en digitale cultuur te versterken en aan de hand van actuele ontwikkelen de betekenis van deze disciplines te verhogen. Research en Development is hierin een verbindende factor. In 2016 waren er 90 mensen werkzaam bij de instelling.</p>
<p>Creatieve industrie is een brede sector die veel disciplines bevat, wat ook tot gevolg heeft dat er verschillende definities van de sector gehanteerd worden, zowel brede als meer beperktere definities. In de CBS Monitor Topsectoren ligt het accent op markt gefinancierde domeinen en minder op publiek gefinancierde domeinen als theaters en publieke- en commerci&euml;le omroepen. De Monitor Creatieve Industrie van iMMovator kiest voor een bredere definitie waarin het accent ook op deze publiek gefinancierde domeinen ligt. Ook het net verschenen Cultuur in Beeld 2017 verwijst naar de definitie gehanteerd in deze monitor van iMMovator. We kunnen de creatieve industrie echter het beste omschrijven als een fijnmazig netwerk van sectoren en partijen.</p>
<p>Omdat creatieve industrie ook sterk verbonden is met de sector economie, heeft specifiek het Stimuleringsfonds niet alleen te maken met subsidie vanuit het ministerie van OCW. Het fonds heeft ook een subsidierelatie met de ministeries van Infrastructuur en Milieu en Buitenlandse Zaken, waarvoor het diverse programma&rsquo;s uitvoert op het gebied van internationalisering (ministeries van OCW en BuZa) en op het gebied van architectuur en ruimtelijk ontwerp (ministeries van OCW en IenM).</p>',
            	'sector_id' => '5'
            ],
            [
            	'title' => 'Letteren &amp; Bibliotheken: St. Lezen, Letterenfonds, Schrijverscentrale, FBJP en KB',
            	'body' => '<p>De letterensector is anders georganiseerd dan de meeste sectoren binnen cultuur. Dat heeft te maken met het feit dat de cultuurproducerende instellingen private partijen zijn. De financiering is dan ook anders, want anders dan in bijvoorbeeld de podiumkunsten, is niet de gehele keten (productie, distributie en exploitatie) publiek gefinancierd. Het sectorinstituut dat net was ontstaan werd ontzien bij de bezuinigingen op cultuur onder Zijlstra, maar de sector kreeg er wel mee te maken, evenals met de gevolgen van de financi&euml;le crisis. Marktpartijen hadden daardoor minder te besteden en bibliotheken kregen te maken met bezuinigingen op lokaal niveau.</p>
<p>In de ondersteuningsstructuur spelen een aantal instellingen een rol, namelijk: het Letterenfonds, de Schrijverscentrale, Stichting Lezen, Fonds Bijzondere Journalistieke Projecten (FBJP). Daarnaast speelt de Koninklijke Bibliotheek (KB) een belangrijke rol, die toelichting behoeft. De KB is een wetenschappelijke instelling met een collectie van 7 miljoen items. De KB heeft een belangrijke co&ouml;rdinerende rol in het netwerk van openbare bibliotheken en heeft sinds de fusie in 2015 de rol en taken van het Sectorinstituut Openbare Bibliotheken overgenomen. De KB bouwt aan de nationale digitale bibliotheek, bibliotheek.nl. De KB heeft de wettelijke opdracht aandacht te besteden aan de onderwerpen die het niveau van lokale bibliotheken overstijgen zoals een gemeenschappelijke infrastructuur, niet-geografisch gebonden doelgroepen en het aansturen van innovatie, kennisdeling en onderzoek in de sector. De KB heeft als stelseltaken: regie en advies, faciliterende en co&ouml;rdinerende taken en de aansturing van grootschalige programma&rsquo;s en projecten voor het hele bibliotheekstelsel. De KB is in deze analyse meegenomen als ondersteunende instelling, maar heeft een andere status omdat deze instellingen niet vanuit de BIS maar de Wsob is gefinancierd.</p>
<p>Stichting Lezen is het kennis- en expertisecentrum voor leesbevordering en literatuureducatie en maakt in die rol deel uit van de Basisinfrastructuur. De stichting zet zich in voor het verbeteren van het leesklimaat en de leescultuur, als onderdeel van het algemene lees- en literatuurbeleid van het ministerie van OCW.</p>
<p>Het Letterenfonds, de Schrijverscentrale en Stichting Lezen zijn onlangs verhuisd naar een gezamenlijk Letterenhuis in Amsterdam met als doel meer onderlinge samenwerking te stimuleren. Het Fonds Bijzondere Journalistieke Projecten heeft gezamenlijke huisvesting met instellingen uit de meer journalistieke hoek, zoals het Huis voor Democratie. De capaciteit sterk verschilt en een instelling als het FBJP met 1,5 fte heeft bijvoorbeeld weinig tot geen mogelijkheden ondersteuning te bieden aan het veld, anders dan het bieden van financiering. De instellingen streven naar intensievere samenwerking om kwetsbaarheid te beperken en meer slagkracht te realiseren.</p>
<p>Om het lezen in Nederland te bevorderen hebben enkele landelijke organisaties, zoals de Stichting Lezen, de CPNB, de Stichting Lezen en Schrijven de krachten gebundeld in de Leescoalitie. Zij voeren activiteiten uit die erop zijn gericht om zoveel mogelijk mensen aan te zetten tot lezen en voorlezen. Ook is er het programma van drie ministeries van OCW, SZW en VWS: <em>Tel mee met taal</em> om het lezen en het plezier in lezen te bevorderen. Hiervan zijn onder meer de KB, de Stichting Lezen en de Stichting Lezen en Schrijven partner.</p>',
            	'sector_id' => '6'
            ],
            [
            	'title' => 'Bovensectoraal Beleid: Boekmanstichting',
            	'body' => '<p>Met het bovensectorale onderwerp Beleid doelen we op de ondersteuningsfuncties gekoppeld aan het cultuurbeleid van de overheid. Volgens de Wet en de Regeling op het Specifiek Cultuurbeleid is er subsidie geoormerkt voor &eacute;&eacute;n instelling met als kernactiviteit het verzamelen en verspreiden van kennis en informatie over kunst en cultuur in beleid en praktijk. De activiteiten van die instelling moeten gericht zijn op het bevorderen en faciliteren van onderzoek en van meningsvorming over de productie, distributie en afname van kunst en cultuur en over het nationale en internationale kunst- en cultuurbeleid. Hiervoor wordt in de regeling als aanduiding Onderzoek &amp; Statistiek gebruikt.</p>
<p>Bovensectoraal beleid is op basis van de regeling door het ministerie van OCW belegd bij de Boekmanstichting, kenniscentrum voor kunst, cultuur en beleid in Nederland. Dit kenniscentrum heeft, volgens het Activiteitenplan 2017-2020, als primaire taak trends en ontwikkelingen in de culturele sector op onafhankelijke wijze en op basis van betrouwbare cultuurcijfers te duiden ten behoeve van de zichtbaarheid van cultuur in het maatschappelijke en politieke krachtenveld. Door zich hier optimaal voor in te zetten, komt de Boekmanstichting naar eigen zeggen tegemoet aan de behoefte van beleidmakers aan evidence-based cultuurbeleid &eacute;n draagt de stichting bij aan de professionalisering van het cultuurbeleid in Nederland.</p>
<p>De Boekmanstichting is er voor iedereen die zich vakmatig bezighoudt met cultuurbeleid, met een perspectief vanuit de culturele sector, overheid, media, wetenschap. De Boekmanstichting bedient daarmee de culturele sector van Kunst, Cultuur, Erfgoed en Creatieve industrie en in mindere mate Media en zoekt daarbij de raakvlakken met andere maatschappelijke domeinen op, te weten: sport, zorg en gezondheid, ruimtelijke ordening.</p>
<p>De Boekmanstichting beschrijft in haar Activiteitenplan 2017-2020 vijf functies die nagenoeg overeenkomen met verschillende in dit onderzoek onderscheiden ondersteuningsfuncties. De functies en de relatie met de in dit onderzoek benoemde functies zijn:</p>
<ul>
<li><em>Duiding</em> (vergelijkbaar met informatievoorziening)<em>: </em>de Boekmanstichting geeft betekenis aan kwantitatieve en kwalitatieve gegevens. Het betreft dataverzameling, beleidsinformatieverzameling, analyse, verklaring en ontsluiting. Met uitvoering van deze functie zet de stichting haar kennis en kunde in voor het duiden van maatschappelijke en sociale trends in het veld van cultuurbeleid.</li>
<li><em>Debat</em> (komt terug in netwerkactivering): de Boekmanstichting jaagt op een onafhankelijke, neutrale wijze het culturele debat aan. De debatfunctie heeft tot doel meningsvorming te bevorderen; de Boekmanstichting biedt een platform voor alle standpunten die er zijn en ontfermt zich over het agenderen van onderwerpen die in ieders belang zijn, maar waarvan niemand zich eigenaar voelt.</li>
<li><em>Documentatie</em> (komt terug in beheer &amp; ontsluiting en informatievoorziening): dit betreft de (digitale) bibliotheek, catalogus, archief, kennisborging, (data)informatieontsluiting en collectiebeheer.</li>
<li><em>Deling</em> (vergelijkbaar met netwerkactivering): deze functie uit zich in het optreden als verbinder; (onverwachte) partijen die elkaars kennis (en bereik) kunnen gebruiken, elkaar kunnen versterken en inspireren, vinden elkaar via de Boekmanstichting. Op die manier draagt de stichting haar platformfunctie uit.</li>
<li><em>Diensten</em> (met lage prioriteit en deze functie komt alleen terug in de vorm van opdrachttaken onder beleidsondersteuning): hieronder verstaat de Boekmanstichting het uitvoeren van werkzaamheden, zoals het doen van onderzoek en het inhoudelijk vormgeven van evenementen, debatten en congressen, voor een opdrachtgever tegen vergoeding.</li>
</ul>
<p>De Boekmanstichting is met 8 fte klein qua omvang, niet alleen in vergelijking met het LKCA als bovensectoraal kennisinstituut voor cultuureducatie en cultuurparticipatie, maar ook in vergelijking met de rijksgefinancierde kennisinstituten in andere maatschappelijke sectoren, zoals is gebleken in het onderzoek &ldquo;De publieke kennisorganisaties&rdquo; van het Rathenau Instituut uit 2016. De Boekmanstichting is ruimschoots de kleinste van de 29 vergeleken (maar sterk verschillende) kennisorganisaties. Daarna komt Geonovum (geo-informatie, door I&amp;M gefinancierd) met 13,4 fte en het Mulier Instituut (sport, door VWS gefinancierd) met 19 fte. De Boekmanstichting kent evenwel veel activiteiten en een divers palet aan ingezette middelen en uitingen op de verschillende functies. De stichting hecht aan wendbaarheid, korte lijnen en beperkte personeelszaken, maar maakt zich gezien de beperkte capaciteit zorgen over het kunnen bieden van evenwichtige en continue ondersteuning aan de volle breedte van de sector.</p>',
            	'sector_id' => '7'
            ],
            [
            	'title' => 'Bovensectoraal Digitalisering: DEN',
            	'body' => '<p>De landelijke ondersteuning op het gebied van digitalisering ligt bij Digitaal Erfgoed Nederland (DEN), het kennisinstituut van de digitale cultuur. DEN is in 1996 gestart als publieksorganisatie door een groep erfgoedinstellingen om samenwerking op het gebied van ICT te stimuleren. Toen de kwaliteitszorg op dit gebied ook belegd werd bij DEN, is DEN in 2005 overgegaan van een vereniging naar een stichting, om de onafhankelijkheidspositie te kunnen waarborgen. DEN ondersteunt erfgoedbeherende instellingen, maar sinds januari 2017 ook cultuurproducerende instellingen, zoals de podiumkunsten. DEN wil, in gezamenlijkheid met cultuurproducerende en erfgoedbeherende instellingen, een actieve bijdrage leveren aan de informatiemaatschappij. DEN bevordert en bewaakt de kwaliteit van digitale dienstverlening en digitalisering, investeert in de kennisontwikkeling, stimuleert de instellingen om te innoveren en aan de eisen van de digitale samenleving te voldoen, versterkt de toekomstvastigheid en publieksgerichtheid van de nationale infrastructuur voor digitaal erfgoed en bewaakt de aansluiting van de Digitale Collectie Nederland op andere nationale en internationale diensten en voorzieningen.</p>
<p>In 2011 is het een voornemen geweest om DEN na de beleidsperiode van 2013-2016 niet meer te financieren vanuit de overheid. Het Ministerie van OCW heeft erkend dat DEN een probleem adresseert dat zonder DEN niet voldoende geadresseerd zou worden, en dat de instellingen in het culturele veld nog steeds behoefte hebben aan ondersteuning op het gebied van digitalisering. Zodoende heeft DEN vanaf 2017 opnieuw een plek gekregen in de basisinfrastructuur. Om de afname van (Europese) projectgelden op te vangen is de formatie van DEN teruggebracht van 16 naar 11 mensen (5,7 fte).</p>
<p>Er zijn andere partijen die zich op hetzelfde terrein begeven als DEN, zoals Beeld en Geluid en EYE voor film en beeld, LIMA specifiek voor de mediakunst, de Rijksdienst voor Cultureel Erfgoed en RKD richting musea en beeldende kunst, Het Nieuwe Instituut voor de creatieve industrie, de Koninklijke Bibliotheek (KB) en het Nationaal Archief voor bibliotheken en archieven, en op erfgoedniveau ook de provincies. Echter, er zijn geen andere partijen die zoals DEN de kennis omtrent digitalisering landelijk verknopen over de sectoren heen. Alleen op Europees gebied speelt Europeana een rol in het vergroten van de bovensectorale samenwerking.</p>
<p>Een aandachtspunt voor DEN is de kwetsbaarheid van de organisatie. De organisatie is klein en de kennis en het netwerk van de directeur zijn cruciaal voor het succes. In de onderwijssector is Kennisnet een vergelijkbare organisatie, die scholen ondersteunt met ICT. Waar DEN 5,7 fte in dienst heeft, heeft Kennisnet 96 fte in dienst. De vergelijking gaat niet volledig op omdat het primair- en voortgezet onderwijs meer afhankelijk is van Kennisnet omtrent de ICT dan de cultuursector van DEN, maar dit laat wel zien dat DEN echt leunt op een paar personen. Op dit moment is DEN doende de vacante positie van directeur in te vullen.</p>',
            	'sector_id' => '8'
            ],
            [
            	'title' => 'Bovensectoraal Ondernemerschap: Cultuur+Ondernemen',
            	'body' => '<p>Cultureel ondernemerschap is al in zwang in het cultuurbeleid sinds staatssecretaris Van der Ploeg in de periode 1998-2002. Hij beschreef Cultureel ondernemerschap als een &lsquo;houding die erop is gericht zoveel mogelijk kunstzinnig, artistiek-cultureel, zakelijk en maatschappelijk rendement te halen uit culturele voorzieningen&rsquo;. Sindsdien heeft cultureel ondernemerschap een belangrijke plaats gekregen in het cultuurbeleid van het rijk, en evenzeer van provincies en gemeenten. Cultureel ondernemerschap is daarmee een belangrijk strategisch en bedrijfsmatig onderwerp voor vrijwel alle culturele instellingen, of zij nu wel of niet subsidie ontvangen, en dat geldt ook voor individuele kunstenaars in hun eigen beroepspraktijk. Onder staatssecretaris Zijlstra werd het begrip verengd tot ondernemerschap en lag de focus op het vergroten van eigen inkomsten, gelijktijdig met lagere rijkssubsidies voor kunst en cultuur. Om de cultuursector te ondersteunen bij het vormgeven en versterken van ondernemerschap heeft het ministerie van OCW het Programma Ondernemerschap Cultuur gestart, dat loopt in de periode 2014-2017, en binnenkort dus eindigt.</p>
<p>Doel van het programma was om het ondernemerschap in de culturele sector te vergroten, o.a. door het verbreden van de financieringsmix, waardoor de sector meer eigen inkomsten zou gaan verwerven. Het programma startte in een periode van economische recessie en bezuinigingen op cultuur, waardoor overheid en sector de focus op ondernemerschap als zeer urgent voelden. Het programma bestond uit vier onderdelen: activiteiten voor kleine culturele instellingen en individuele kunstenaars en creatieve makers (uitgevoerd door Cultuur+Ondernemen), het opleidingsprogramma Leiderschap in Cultuur, LinC, uitgevoerd door de Universiteit Utrecht en Kennisland in samenwerking met de HKU en Coaching in de Cultuur), Wijzer Werven, training en coaching van culturele ANBI&rsquo;s op het gebied van financieringsmix en fondsenwerving (uitgevoerd door Van Dooren Advies en Charistar in samenwerking met Berenschot) en het uitvoeren van de campagne &lsquo;Cultuur, daar geef je om&rsquo; (uitgevoerd door het ministerie van OCW zelf).</p>
<p>Naast Cultuur+Ondernemen en de reeds genoemde uitvoerders van het programma Ondernemerschap Cultuur zijn er veel andere partijen die het ondernemerschap in de cultuursector ondersteunen. Voorbeelden zijn: provinciale steunfuncties, zoals bkkc in Noord-Brabant, provinciale cultuurfondsen zoals Cultuurfonds Gelderland, grote culturele instellingen die hun collega&rsquo;s helpen, brancheorganisaties, onderwijsinstellingen en commerci&euml;le onderzoeks- en adviesbureaus.</p>
<p>Cultuur+Ondernemen (C+O) wordt gesubsidieerd voor ondersteuning bij ondernemerschap. C+O is het kenniscentrum voor ondernemerschap in de cultuursector en is tot stand gekomen in 2010 door een fusie van Kunstenaars&amp;Co, dat zich richtte op individuele kunstenaars, en Kunst &amp; Zaken, dat was gericht op culturele instellingen en het bedrijfsleven. In deze inleiding wordt de bijzondere positie van C+O qua financiering en dienstverlening, in het bijzonder de cultuurleningen uitgebreid beschreven.</p>
<p><em>Financiering en waardering van Cultuur+Ondernemen</em></p>
<p>C+O en zijn voorgangers kennen een langere subsidiegeschiedenis met het Ministerie van OCW. Voor 2013 ontving de instelling jaarlijkse instellingsubsidies van het ministerie. Ook werden in het verleden programma&rsquo;s en opdrachttaken bij C+O en zijn voorgangers ondergebracht door het ministerie, waaronder de ontwikkeling van de Code Governance Cultuur en het programma Cultuurmecenaat.</p>
<p>Sinds 2013 ontvangt C+O vanuit het Programma Ondernemerschap Cultuur een projectsubsidie van het ministerie van OCW, die bestemd is voor het totale activiteitenpakket van de instelling. Het programma eindigt formeel per 2017. De dienstverlening van C+O binnen dit programma is na twee jaar, in 2015, niet formeel, extern ge&euml;valueerd, zo bleek uit onderzoek van DSP naar het programma. Evaluatie na twee jaar was &eacute;&eacute;n van de uitgangspunten van het programma. Ook in 2017 en 2018 stelt het Ministerie van OCW subsidie beschikbaar voor een ondersteunende functie voor ondernemerschap. In dit verband ontvangt C+O subsidie voor de jaren 2017-2018. Nog onbekend is of deze functie na 2018 zal blijven bestaan en, zo ja, in welke vorm. Verder realiseert C+O inkomsten uit publieke (o.a. sociale fondsen) en private bronnen (fondsen en opdrachtgevers).</p>
<p>Uit interviews met stakeholders in het kader van het evaluatieonderzoek van het Programma Ondernemerschap Cultuur rijst het beeld op dat C+O goed is ingebed in de culturele sector, gebruik maakt van een groot netwerk en dat het aanbod van C+O veel wordt afgenomen (met name de activiteiten op het vlak van cultural governance). Maar het is wel de vraag is of alle disciplines in gelijke mate aan bod komen (de beeldende kunst zou oververtegenwoordigd zijn) en of alle landsdelen in gelijke mate bediend worden. Het is echter onvoldoende duidelijk hoe het activiteitenprogramma van C+O zich verhoudt tot het Programma Ondernemerschap Cultuur. Het onderzoek concludeert dat onduidelijk is in welke mate de afzonderlijke activiteiten van C+O (deels) gesubsidieerd zijn of (deels) commercieel worden uitgevoerd. Deze onduidelijkheid kwam nadrukkelijk ook naar voren tijdens de werksessie.</p>
<p>De Raad voor Cultuur onderstreepte in zijn advies uit 2016 het belang van de functie van C+O voor de culturele sector. Het is nuttig dat culturele instellingen, kunstenaars en creatieven ondersteund worden bij de professionalisering van hun ondernemerschap en toegang krijgen tot laagdrempelige financieringsproducten. De raad miste in de subsidieaanvraag een analyse van de behoeften in het veld aan deze diensten en een stakeholdersanalyse. De raad vond het niet duidelijk hoe C+O zich verhoudt ten opzichte van andere (regionale en lokale) organisaties die ondernemerschap in de cultuursector ondersteunen.</p>
<p>Het ministerie van OCW stelt nadrukkelijk als voorwaarde dat de activiteiten van C+O niet marktverstorend mogen werken op bijvoorbeeld de dienstverlening van de Kamers van Koophandel, culturele brancheorganisaties of commerci&euml;le advies- en coachingsbureaus. Daarnaast moet er bij de uitvoering van de activiteiten gebruik worden gemaakt van de al bestaande netwerken voor individuele kunstenaars en creatieve makers.</p>
<p>C+O spreekt zich in zijn openbare communicatie (website, jaarverslagen, publicaties) niet uit over zijn positie in de markt van onderzoeks- en adviesbureaus en hoe marktverstoring voorkomen wordt. Opdrachten die C+O uitvoert voor instellingen (al dan niet in opdracht van gemeenten) kunnen in veel gevallen ook door private/commerci&euml;le bureaus worden uitgevoerd. C+O legt niet uit hoe de publieke en private diensten met elkaar samenhangen en hoe de financieringsstromen lopen. C+O legt dit wel uit in de monitorgesprekken met het ministerie. Het ministerie accepteert deze uitleg, maar benadrukt het belang van transparantie over de dienstverlening en prijsstelling. Uit de gesprekken en de sessie in het kader van het onderzoek blijkt dat het veld vindt dat C+O hier onvoldoende transparant over communiceert.</p>
<p><em>Dienstverlening door Cultuur+Ondernemen</em></p>
<p>De hoofdtaak van C+O is dienstverlening aan spelers in de cultuursector. Omdat dit in een aantal gevallen dienstverlenging betreft aan individuele spelers en niet aan de sector als geheel, is dit niet als een van de in dit onderzoek onderscheiden ondersteuningsfuncties op te vatten. Daarom wordt de dienstverlening van C+O in deze inleidende paragraaf uitgebreid toegelicht.</p>
<p>C+O legitimeert zijn dienstverlening vanuit de visie dat het belang van publiek-private financiering van cultuur verder zal toenemen en dat instellingen en makers behoefte hebben aan ondersteuning bij het realiseren van een gezond bedrijfsmodel. Daarvoor zijn kennis, vaardigheden en netwerken rondom publiek private financiering nodig. De rol die de overheid heeft ten opzichte van de culturele sector transformeert van subsidi&euml;nt naar medespeler, te midden van andere financiers. De doelgroepen van C+O zijn culturele organisaties (vooral klein en middelgroot, in principe niet de BIS-instellingen), zelfstandig werkende kunstenaars en zogenaamde creatieven. C+O ondersteunt deze spelers bij professionalisering, bij het vinden van passende financiering, bij het vinden van nieuwe businessmodellen en bij het &lsquo;up to date&rsquo; houden en/of optimaliseren van de governance. C+O verricht de volgende activiteiten die (mede) betaald worden vanuit het OCW-programma Ondernemerschap Cultuur:</p>
<ul>
<li>Startadviezen aan instellingen, creatieve ondernemingen, individuele kunstenaars en creatieven, evenwichtig verdeeld over de verschillende doelgroepen, disciplines en regio&rsquo;s. Een gratis startadvies kan aanleiding geven voor een intern of extern betaald adviestraject.</li>
<li>Advies en begeleiding bij het opzetten en vernieuwen van financi&euml;le diensten. Het doel hiervan is om de financieringsmogelijkheden en -diversiteit te vergroten (nieuwe verdienmodellen en daarop afgestemde financieringsmix) en zo meer cultuurproductie en -distributie mogelijk te maken. C+O zet instrumenten in als leningen, microkredieten en garantstellingen; zie ook de uitwerking van cultuurleningen hierna.</li>
<li>Advies en ondersteuning aan besturen en raden van toezicht bij het toepassen van de Governance Code Cultuur. In 2017 is een herziening van de Code voorzien.</li>
<li>Onderzoek naar kansen, voorwaarden en bruikbaarheid van nieuwe financieringsmodellen in de cultuursector en deling van kennis/inzichten uit onderzoek met de sector.</li>
</ul>
<p><em>Cultuurleningen via Cultuur+Ondernemen</em></p>
<p>C+O biedt cultuurleningen aan voor professionele kunstenaars en culturele organisaties. Een lening legt het accent op investeren en terugverdienen en bevordert ondernemerschap. Dat is een groot verschil met subsidies of ander geefgeld. Leningen horen thuis in een succesvolle en moderne financieringsmix van de kunst- en cultuursector.</p>
<p>Leningen uit de markt (van banken, financi&euml;le instellingen, of private investeerders) zijn nog nauwelijks toegankelijk voor kunstenaars of culturele organisaties. De rendementsverwachting is vaak te laag, de risico&rsquo;s zijn te groot, en het onderpand is meestal onvoldoende. Omdat de markt hier faalt, biedt C+O (naast onder meer het Fonds Kwadraat) cultuurleningen aan, laagdrempelig en tegen gunstige condities. C+O heeft daarvoor een infrastructuur opgezet, waarin het door C+O opgerichte Fonds Cultuur +Financiering (FCF) een centrale rol speelt. FCF (een onafhankelijke fondsmanager) beoordeelt de aanvragen financieel en is de contractpartij voor elke lening. Daarmee is de adviesfunctie van C+O feitelijk en ook functioneel gescheiden van de financieringsfunctie.</p>
<p>De cultuurleningen (maximaal &euro; 40.000 tegen 3%) beogen een spin off te realiseren naar andere financiers (103 toegekende leningen in de periode 2015-2016 met een financieringsproductie van ruim &euro; 1,2 mln.). De cultuurleningen helpen bij het opzetten en verwerven van crowdfunding, maar ook bij het aantrekken van bancaire financieringen. Daarnaast staat FCF regelmatig garant op bancaire kredietverlening. C+O werkt samen met een aantal (naast OCW) lokale partners, zoals gemeenten, provincies, lokale fondsen en lokale kenniscentra. Deze partners dragen bij aan de distributie van de leningen (via laagdrempelige lokale &lsquo;loketten&rsquo;) en aan de financiering ervan (bijdrage aan leenkapitaal en bijdrage aan uitvoerings- en communicatiekosten). Het aantal regionale partijen wordt gestaag uitgebreid (gesprekken worden gevoerd met Rotterdam en Maastricht).</p>
<p>Het palet aan leningen bestaat thans uit Regionale cultuurleningen (inmiddels voor Amsterdam, Utrecht, Noord-Brabant en Almere), Talentleningen (OCW, landelijke spreiding) en Culturele microkredieten. De Regionale cultuurleningen en de Talentleningen (alle tegen 3%) zijn de kernproducten. De Culturele microkredieten (rente 6%) zijn een terugvaloptie. De leningen, zo blijkt in de praktijk van C+O, stellen de kunstenaar of culturele organisatie wel in staat om andere inkomsten te genereren. De talent- en cultuurleningen versterken de marktpositie en het verdienpotentieel van kunstenaars, culturele organisaties en creatief ondernemers.</p>
<p>C+O stelt op basis van eigen onderzoek (met inzet van diverse instrumenten) vast dat het aanbod van leningen voorziet in een behoefte. De belangstelling voor de leningen is volgens verwachting, zowel in het aantal aanvragen en toekenningen als in de aangevraagde bedragen. De leningen blijken breed inzetbaar in de sector. Kunstenaars en organisaties maken er gebruik van (muziek, film, tv, design, mode, beeldende kunst, podiumkunsten, literatuur), en de toepassing is breed (productiekosten, marketing &amp; communicatie, apparatuur &amp; instrumenten, studio &amp; werkplaats). De afschrijvingen op leningen zijn beperkt. De gekozen structuur, met het Fonds Cultuur+Financiering als centrale speler en C+O als begeleider en adviseur, functioneert naar behoren. Leningnemers zijn in het algemeen tevreden als het gaat om direct contact met een medewerker en waarderen de mogelijkheid om hun plannen toe te lichten.</p>
<p>Ondanks de goede voorbeelden blijft de bekendheid en populariteit van de leningen vooralsnog beperkt. De sector staat terughoudend tegenover leningen in de financieringsmix. Een lening komt niet in de plaats van subsidies of andere inkomsten, want leningen op zichzelf zijn geen inkomsten. De lening moet immers altijd worden terugbetaald. Ook laat de kwaliteit van de aanvragen regelmatig te wensen over: zelden is een aanvraag in &eacute;&eacute;n keer goed. Dat is niet vreemd. Een lening is een nieuw instrument in de financieringsmix. De meeste kunstenaars en culturele organisaties zijn nog ingesteld op het aanvragen van subsidies, naast het genereren van eigen inkomsten. Lenen om te investeren en te innoveren past nog niet in het plaatje. Een deel van de potenti&euml;le leningnemers ziet de lening hooguit als een laatste redmiddel, als subsidies of andere inkomsten buiten beeld zijn.</p>
<p>In de kunst- en cultuursector is nog lang geen sprake van een volwaardig financieel ecosysteem, zo stelt C+O zelf. De sector is sterk subsidiegedreven, kenmerkt zich door hoge risico&rsquo;s en lage rendementen en heeft bovendien weinig ervaring met voorfinanciering, investeren en terugverdienen.</p>',
            	'sector_id' => '9'
            ],
            [
            	'title' => 'Bovensectoraal Internationalisering: DutchCulture',
            	'body' => '<p>Het bovensectorale thema internationalisering is een taak van de sectorale fondsen, maar is ook expliciet belegd bij DutchCulture, centrum voor internationalisering. DutchCulture is er voor culturele professionals en diplomaten, overheden (nationaal, regionaal, stedelijk en de Europese Unie). Verder richt het zich op fondsen, instituten en overige partijen in het onderwijs, pers &amp; media, het internationale veld en publiek. Kortom, iedereen die zich op een bepaalde manier bezighoudt met internationalisering van cultuur. Doel van DutchCulture is internationale samenwerking in kunst, cultuur en erfgoed te steunen en stimuleren. OCW en Buitenlandse Zaken hebben in het beleidskader internationaal cultuurbeleid 2017-2020 voor DutchCulture een aantal focuslanden benoemd voor de beleidsperiode 2017-2020. Dat zijn Belgi&euml;/Vlaanderen, China, Duitsland, Frankrijk, Indonesi&euml;, Turkije, de Verenigde Staten en het Verenigd Koninkrijk.</p>
<p>DutchCulture is een fusieorganisatie van Stichting Internationale Culturele Activiteiten (SICA), Trans Artists and Media DESK Netherlands en is in deze hoedanigheid actief sinds 2013. Onderdeel van DutchCulture is Creative Europe, voor informatie en advies over financiering in Europese context.</p>
<p>DutchCulture heeft ruim 23 fte in dienst plus twee freelancers. Het veld heeft de indruk dat DutchCulture daarmee capaciteit tekort komt om hen echt goed te kunnen bedienen op de benodigde functies.. Mogelijk kunnen betere afstemming met andere partijen die een rol spelen bij internationalisering, het verzorgen van een totaaloverzicht wat er allemaal gebeurt aan internationalisering en een heldere focus daarbij helpen. DutchCulture kan andersom ook weer doorverwijzen naar meer sectorspecifieke partijen.</p>',
            	'sector_id' => '10'
            ],
            [
            	'title' => 'Bovensectoraal Cultuureducatie &amp; Cultuurparticipatie: LKCA en FCP',
            	'body' => '<p>Cultuureducatie en cultuurparticipatie vormen een bovensectoraal onderwerp, maar wijken af van de andere bovensectorale onderwerpen doordat het veld er op een andere manier mee bezig is. Cultuureducatie is een primaire taak van een aantal cultuureducatieve instellingen en het is een belangrijke secundaire taak van cultuurproducerende instellingen. Verder bestaat een aanzienlijk deel van cultuurparticipatie uit de beoefening van amateurkunst, door individuen en door een zeer omvangrijk en divers geheel van verenigingen en andere instellingen. Dat maakt dat cultuureducatie en cultuurparticipatie naast een bovensectoraal thematisch onderwerp ook een soort sector op zich vormt die alle culturele disciplines omvat.</p>
<p>Op rijksniveau zijn er twee instellingen bij wie de ondersteuning voor deze bovensectorale onderwerpen is belegd, namelijk het Landelijk Kennisinstituut Cultuureducatie en Amateurkunst (in de rest van dit rapport LKCA) en het Fonds voor Cultuurparticipatie (FCP).</p>
<p>Het LKCA staat voor de waarden van cultuureducatie en actieve cultuurparticipatie en draagt deze actief uit. Het LKCA wil ervoor zorgen dat iedereen op school en in de vrije tijd goede cultuureducatie krijgt en dat cultuurparticipatie voor iedereen mogelijk is. Het kennisinstituut LKCA is in 2012 voortgekomen uit een fusie van Kunstfactor, dat zich richtte op amateurkunst, en Cultuurnetwerk, kenniscentrum voor cultuureducatie. Het LKCA richt zich op professionals die werken voor cultuur op school of in de vrije tijd. Het LKCA had eind 2016 een formatie van 52 fte. Het LKCA ontving in 2016 &euro; 5,3 mln subsidie.</p>
<p>Het FCP financiert sinds 2009 instellingen en initiatieven in de vorm van regelingen en stimuleringsprogramma&rsquo;s op het gebied van cultuureducatie en cultuurparticipatie en heeft in het verlengde daarvan enkele ondersteunende werkzaamheden. Het FCP ondersteunt en verbindt naar eigen zeggen mensen, organisaties en overheden die werk maken van cultuurparticipatie. De drie programma&rsquo;s zijn Cultuureducatie met Kwaliteit, Innovatie in Cultuur &ndash; maak het mee en Cultuur maakt iedereen zichtbaar. Het FCP heeft een jaarlijkse begroting van &euro; 25,3 mln, waarvan &euro; 22,5 mln via programma&rsquo;s wordt besteed aan financiering en subsidi&euml;ring van het veld. Het FCP had eind 2016 een formatie van 30 medewerkers, bijna 25 fte.</p>
<p>In de aanloop naar de beleidsperiode 2017-2020 hebben het FCP en het LKCA een gezamenlijke ambitie geformuleerd. Zij trekken samen op, ieder vanuit zijn eigen onafhankelijke rol, om nieuwe ontwikkelingen te signaleren, agenderen en stimuleren in de werkvelden cultuureducatie en cultuurparticipatie. Zij doen dit door het delen van praktijkervaringen, het verbinden van netwerken en het ondersteunen van innovatieve en inspirerende projecten gericht op onderwijs, samenleving, infrastructuur en waardering. Het FCP stimuleert daarbij ontwikkeling, zichtbaarheid en verbinding van cultuureducatie en cultuurparticipatie via subsidieregelingen en activiteiten, gericht op de doelgroepen die het FCP ondersteunt. Het LKCA stimuleert ontwikkeling door ontmoeting en debat en door te voorzien in kennis en kaders. Het LKCA houdt daarbij een spiegel voor door goede voorbeelden en het bieden van inzicht in relevante ontwikkelingen op (inter)nationaal gebied.</p>
<p>Voor de branche met aanbieders van cultuureducatie en cultuurparticipatie zelf, dus instellingen zoals kunstencentra en verenigingen zijn talloze koepels, brancheorganisaties, vakverenigingen, bonden en vakbonden actief in ondersteuning. De voornaamste speler in cultuureducatie is Cultuurconnectie. Ook voor de ondersteuning van het onderwijs op het gebied van cultuureducatie zijn diverse organisaties actief, zoals de Vereniging Onderwijs Kunst &amp; Cultuur (Vonkc), Algemene Vereniging Schoolleiders (AVS), Vereniging van Cultuurprofielscholen (VCPS), nationaal expertisecentrum leerontwikkeling SLO en dergelijke. Bij de beleidsvorming op het gebied van cultuureducatie en cultuurparticipatie zijn overheden betrokken en ondersteunen elkaar, deels ook via verbanden als de VNG en het IPO.</p>
<p>Op het gebied van cultuureducatie zijn veel regionale en lokale ondersteunende instellingen actief. Dit doen zij in verschillende rollen en functies, soms op meer beleidsmatige en inhoudelijke terreinen zoals kennis, informatie en deskundigheid, soms meer praktisch als intermediair tussen scholen, culturele instellingen en verenigingen en zelfstandige professionals. Het samenspel met deze instellingen is verbeterd, maar soms staan activiteiten nog op gespannen voet, zo merken spelers in het veld op. Het LKCA richt zich op landelijke activiteiten en beperkt zich in lokale activiteiten, om zo voorkomen dat overlap ontstaat met wat regionale en lokale ondersteunende partijen (kunnen) doen. Daarbij helpt het dat het LKCA het landelijke geheel overziet, waar deze organisaties een kleiner gebied bestrijken.</p>
<p>Het LKCA richt zich in principe niet op individuen die les krijgen of kunst beoefenen, maar op de professionals in cultuureducatie en cultuurparticipatie. De professionele partijen die het meest bezig zijn met cultuureducatie behoren tot de cultuursector en het onderwijs. Vanwege de verbindingen met andere domeinen zoals het sociaal domein, zorg en welzijn, sport, openbare ruimte en community arts (sociaal-maatschappelijke vraagstukken) richt het LKCA zich ook op zzp&rsquo;ers of professionals die buiten de culturele sector en het onderwijs werkzaam zijn. Dat maakt het werkveld van het LKCA zeer breed en divers.</p>',
            	'sector_id' => '11'
            ],
        ];

        DB::table('toelichtingsectors')->insert($toelichtingsectors);
    }
}



