<?php

use Illuminate\Database\Seeder;

class ToelichtingsectorsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('toelichtingsectors')->delete();

        $toelichtingsectors = [
            [
            	'title' => 'Podiumkunsten',
            	'body' => '<p>De sector podiumkunsten is een brede en diverse sector met vele genres, die in toenemende mate in elkaar overlopen. Een deel van de professionele podiumkunsten is rijksgesubsidieerd, deels direct binnen de Basisinfrastructuur, deels via het Fonds Podiumkunsten (FPK), dat hiervoor in totaal bij de start van de huidige cultuurnotaperiode een budget van 62 miljoen euro per jaar heeft. Ook andere overheden subsidi&euml;ren delen van het aanbod aan podiumkunsten, maar er is ook een grote en brede vrije sector die zonder subsidie opereert. De presentatieplekken voor de podiumkunsten, vooral concertzalen, schouwburgen en theaters, maar ook festivals, worden grotendeels lokaal gesubsidieerd, maar ook daar is een grote vrije sector van commerci&euml;le theaters en festivals. De ondersteuningsstructuur richt zich op het functioneren van de gehele sector podiumkunsten, met een focus op de professionele en gesubsidieerde cultuurproducenten. </p>

<p>Tot 2013 bestonden er drie sectorinstituten, te weten Theater Instituut Nederland (TIN), Muziek Centrum Nederland (MCN) en het Nederlands Muziek Instituut (NMI). De sectorinstituten TIN en MCN zijn opgeheven als gevolg van de bezuinigingen in 2012. Ook de rijkssubsidie voor NMI is stopgezet, maar die instelling bestaat nog dankzij enige financiering van de gemeente Den Haag en intensieve samenwerking met onder meer het Haags Gemeentearchief. Het FPK heeft sindsdien enkele ondersteunende activiteiten naar zich toegetrokken. Een deel van de eerder wel belegde besteltaken en dus ondersteuningsfuncties wordt daarmee ingevuld door het FPK. Ook brancheverenigingen, zelfstandige stichtingen en andere instellingen zoals de Universiteit van Amsterdam vervullen taken, maar zonder structurele rijksfinanciering daarvan. Andere taken zijn gestopt. In de paragrafen per functie wordt beschreven welke andere partijen zoals brancheverenigingen een rol spelen delen van de uitvoering van ondersteunende taken. </p>',
            	'sector_id' => '1'
            ],
            [
            	'title' => 'Beeldende Kunst',
            	'body' => '<p>De sector beeldende kunst bestrijkt een bont palet aan spelers, zoals kunstenaars, kunstenaarsinitiatieven, presentatie-instellingen, galeries, musea, postacademische instellingen en festivals. Voor beeldende kunst heeft nooit een specifiek sectorinstituut bestaan met een aantal besteltaken c.q. ondersteuningsfuncties. Bij de bezuinigingsronde van 2013 zijn grote intermediaire instellingen zoals SKOR, Stichting Kunst en Openbare Ruimte en NIMk, Nederlands Instituut voor Mediakunst verdwenen. De WWIK werd afgeschaft en bij het Mondriaan Fonds is 40% van het budget bezuinigd.</p>

<p>De organisatiegraad in de sector was een paar jaar geleden relatief laag. Voor de sector beeldende kunst is, mede bij gebrek aan sectorinstituut, het Mondriaan Fonds vanuit de Basisinfrastructuur-ondersteuning ingesprongen voor het invullen van een aantal van de ondersteuningsfuncties die anders geheel afwezig zouden zijn. Daarnaast groeide sinds de bezuinigingen het besef dat de sector zich zelf beter moest organiseren om het publieke belang van de beeldende kunst beter voor het voetlicht te krijgen. De noodzaak voor beeldend kunstenaars, beeldende kunstmusea, galeries en presentatie-instellingen om hun belangen te behartigen werd zeer urgent. </p>

<p>Deze urgentie heeft geleid tot BKNL, een overlegstructuur die wordt gefaciliteerd door het Mondriaan Fonds waarin alle geledingen van de beeldende kunst zijn vertegenwoordigd, inclusief de meer bovensectorale belangenorganisaties Kunstenbond (voorheen FNV KIEM) en Kunsten &rsquo;92. Het Mondriaan Fonds heeft de afgelopen vijf jaar op verzoek van BKNL bijeenkomsten gehost, voorgezeten, voorbereid en verslagen. Onderzoeken in opdracht van BKNL zijn door het Mondriaan Fonds gefinancierd en mede begeleid, zoals de Collectieve Selfie, het onderzoek naar (de behoefte aan) een honorariumrichtlijn, het evalueren van de richtlijn en van het reglement dat voorziet in de tegemoetkoming van honoraria. Geen van de in BKNL participerende organisaties beschikt over de mankracht en de middelen om die taken te kunnen dragen. </p>

<p>Verder zijn in de sector beeldende kunst twee belangenorganisaties opgericht: de vereniging van presentatie-instellingen De Zaak Nu en de vereniging Platform Beeldende Kunst (Platform BK) voor beeldend kunstenaars, ontwerpers en andere culturele producenten. Daarnaast vervullen diverse spelers een eigen rol in de ondersteuning van de sector, zoals Kunsten&rsquo;92, de Museumvereniging, Federatie Cultuur, de Kunstenbond, Dhaps, Binoq, Laps, KNAW, Boknet, NGA en BBKnet.</p>

<p>In het onderzoek naar de ondersteunende activiteiten in de beeldende kunst ligt de nadruk op het Mondriaan Fonds. Het fonds is een uitvoeringsorganisatie van het ministerie met een beleidsvoorbereidende taak op het gebied van beeldende kunst en erfgoedactiviteiten. Het fonds vangt bij gebrek aan sectorinstituut in deze sector verschillende taken op die nergens formeel zijn belegd, maar ontvangt daarvoor geen financiering. Het Mondriaan Fonds is ontstaan uit een fusie van het Fonds BKVB en de Mondriaan Stichting. Sinds de fusie is er &eacute;&eacute;n loket voor individuele aanvragers en instellingen op het gebied van beeldende kunst en cultureel erfgoed. </p>

<p>Het Mondriaan Fonds heeft jaarlijks circa 26 miljoen euro te besteden. Het grootste deel van dit budget komt van het ministerie van OCW. Het Mondriaan Fonds bevordert bijzondere en vernieuwende projecten en activiteiten van beeldend kunstenaars, bemiddelaars (curatoren en critici), musea en andere erfgoedinstellingen, presentatie-instellingen, archieven, galeries en opdrachtgevers. Alle bijdragen hebben tot doel het stimuleren van de productie en de presentatie van relevante beeldende kunst en erfgoed uit Nederland in binnen- en buitenland op die plekken waar de markt dit (nog) niet doet. Per jaar worden honderden projecten in Nederland en daarbuiten ondersteund. Daarnaast biedt het fonds stimuleringsprogramma&rsquo;s voor innovatie en promotie, die aanjagen en agenderen. Bij het Mondriaan Fonds werken 34 mensen. Bij de beoordeling van aanvragen wordt het fonds geadviseerd door 75 deskundigen.  </p>',
            	'sector_id' => '2'
            ],
            [
            	'title' => 'Erfgoed',
            	'body' => '<p>Erfgoed in Nederland omvat een zeer ruim domein met onder andere monumenten, landschappen, archieven, (collecties in) musea, verzamelingen, archeologische vondsten en immaterieel erfgoed (tradities, verhalen en dialecten). In dit onderzoek gaat het, zoals door het ministerie van OCW aan ons is gevraagd, specifiek over erfgoed exclusief monumenten en archieven, en ligt de nadruk op ondersteuning van de musea. De landelijke ondersteuning in de culturele sector op het gebied van Erfgoed ligt bij het Nederlands Instituut voor Kunstgeschiedenis (hierna: het RKD), en in praktijk ook bij het Mondriaan Fonds, het publieke stimuleringsfonds voor beeldende kunst en cultureel erfgoed.</p>

<p>Het RKD maakt kennis en informatie van de kunst van de Nederlanden in internationale context wereldwijd toegankelijk voor musea, wetenschap en publiek. Het is een kennisinstituut met zowel een onderzoeksfunctie als een collectie- en publieksfunctie en heeft als kerntaak het verzamelen, beheren, beschikbaar stellen en presenteren van archief-, documentatie-, en bibliotheekmateriaal van en over de kunst van de Nederlanden in internationale context en het bevorderen van onderzoek hiernaar. De driehoek waarin het RKD opereert wordt gevormd door het publiek (fysiek en digitaal), de musea en de wetenschap. Met deze drie velden wordt veel samengewerkt. De organisatie bestond in eind 2016 uit 54 fte. </p>

<p>Het Mondriaan Fonds bevordert bijzondere en vernieuwende projecten en activiteiten in beeldende kunst en erfgoed. Voor erfgoed kunnen musea en andere instellingen terecht bij het Mondriaan Fonds voor projectinvesteringen, opdrachten, programmering en bijdragen aan collecties. De ondersteunende taken voor het erfgoedveld die het Mondriaan Fonds op zich heeft genomen, maken geen deel uit van de opdracht of financiering van het fonds. In de paragraaf over de sector beeldende kunst staat een uitgebreidere toelichting op het Mondriaan Fonds.</p>

<p>Andere spelers in het veld van ondersteuning in de erfgoedsector zijn CODART, NICAS, ESNA, VNK, OSK, de Koninklijke Bibliotheek, onderzoeksinstituten en universiteiten, DEN, DutchCulture, Rijksdienst voor Cultureel Erfgoed en individuele musea. Verder wordt opgemerkt dat Erfgoed Nederland, dat op 1 januari 2007 was ontstaan uit het samengaan van het Nationaal Contact Monumenten (NCM), de Stichting voor de Nederlandse Archeologie (SNA), de erfgoedkoepel voor de Documentaire informatievoorziening en het archiefwezen (DIVA), en Erfgoed Actueel, als gevolg van de rijksbezuinigingen in 2012 is opgeheven.  </p>',
            	'sector_id' => '3'
            ],
            [
            	'title' => 'Film',
            	'body' => '<p>De filmsector is internationaal geori&euml;nteerd, wat betreft profilering, structuur en financiering. De keten van productie, distributie en exploitatie is niet instellingsgericht maar projectmatig georganiseerd en overwegend privaat gefinancierd. De sector bestaat uit kleine en een aantal middelgrote ondernemingen en een groot aantal zzp&rsquo;ers. De exploitatiezijde wordt door een aantal grote internationaal opererende spelers gedomineerd. Er is een klein aantal instellingen, namelijk filmfestivals, lokale filmtheaters en EYE, die mede met subsidies hun taak uitoefenen. </p>

<p>Het onderzoek naar de ondersteuningsstructuur heeft primair betrekking op de ondersteunende activiteiten van het Filmfonds en EYE. Een deel van de ondersteuningsfuncties wordt door deze instellingen uitgevoerd, al dan niet als wettelijke taak. EYE en het Filmfonds nemen, zoals uit dit onderzoek blijkt, meer ondersteunende taken op zich dan binnen hun primaire opdrachten bij hen zijn belegd, en daar staat ook geen aanvullende financiering tegenover. </p>

<p>Er is geen koepelorganisatie in de filmsector. Elke beroepsgroep kent zijn eigen vereniging, en dat zijn er circa dertig. Bij strategische belangen die de gehele filmproductiesector aangaan nemen de producentenverenigingen samen met de verenigingen van scenaristen en regisseurs het voortouw, waarbij ook partijen zoals Kunsten&rsquo;92 en de Kunstenbond een rol spelen. Diverse ondersteunende functies zijn met de opheffing van Binger Filmlab, NIAF en het Mediafonds verdwenen. De filmfestivals die in de basisinfrastructuur zijn opgenomen, namelijk het NFF, IDFA, IFFR en Cinekid, maar ook de festivals die door het Filmfonds worden ondersteund, spelen belangrijke rollen in de ondersteuning van de filmsector. Die rollen lichten we in het hoofdstuk over de filmsector toe, hoewel we ons realiseren dat de beschrijvingen niet volledig zijn en daarmee onvoldoende recht doen aan de inspanningen van deze instellingen voor de ontwikkeling van de filmsector. </p>

<p>Het Filmfonds heeft als primaire taak de financiering van de Nederlandse filmproducties van korte films, speelfilms en documentaires tot animatie en innovatieve producties, en filmactiviteiten zoals festivals, training, publicatie en onderzoek. Het gemiddelde beschikbare jaarbudget van het Filmfonds voor subsidieverlening en activiteiten in de beleidsperiode 2017-2020 is 49 miljoen euro. Aanpalend aan de beleidspijlers talentontwikkeling, innovatie, internationalisering en professionalisering die leidend zijn voor de regelingen entameert het Filmfonds ook flankerende beleidsactiviteiten. In de financiering van producties hebben naast het Filmfonds ook andere publieke partijen een rol, zoals het NPO-fonds en de publieke omroepen, en voor specifieke innovatieve of interdisciplinaire producties in samenwerking met het Filmfonds ook het Stimuleringsfonds Creatieve Industrie en het Mondriaan Fonds. Internationaal is het Europese coproductiefonds Eurimages een belangrijke financier voor coproducties net als nationale en regionale fondsen in andere landen. </p>

<p>Net als filmfondsen in andere landen, voert het Filmfonds in directe samenhang met zijn centrale rol als financier een aantal ondersteunende functies uit, zoals internationale activiteiten, analyse en onderzoek en in het bijzonder de Netherlands Film Commission. In het beleidskader 2017-2020 is de Netherlands Film Commission als ondersteunende functie bij het Filmfonds belegd, voor de internationale promotie van Nederland als productieland. De Film Commission is het centrale aanspreek- en servicepunt voor buitenlandse producenten die in Nederland (delen van) hun productie willen uitvoeren en treedt op als de liaison tussen deze producenten en de bedrijven en professionals in de Nederlandse creatieve industrie. Regionaal en lokaal komt ook dergelijke ondersteuning voor, onder meer provinciale en stedelijke film commissioners die samenwerken met de Netherlands Film Commission op nationaal niveau.</p>

<p>EYE is het Nederlandse filminstituut met primaire museale en erfgoedtaken en enkele kennisgedreven ondersteuningsfuncties. EYE is sinds 2010 onderdeel van de ondersteuningsstructuur en is een fusieorganisatie, ontstaan uit het Filmmuseum, Holland Film, het Nederlands Instituut voor Filmeducatie (NIF) en de Filmbank, waarvan niet alle taken zijn behouden wegens gelijktijdige bezuinigingen. Bij EYE zijn wettelijke taken neergelegd op het gebied van internationale promotie en landelijke educatie. Daarbij wordt opgemerkt dat educatie geen onderdeel uitmaakt van de in dit onderzoek beschouwde ondersteuningsfuncties. EYE heeft vanuit zijn rol als filmmuseum ook activiteiten op het gebied van beheer en ontsluiting van de filmcollectie. Mede dankzij de aanvullende financiering via het btw-convenant heeft EYE in nauwe samenspraak met de sector nog een aantal taken op zich kunnen nemen, zonder dat dit als opdracht is belegd, op het gebied van deskundigheidsbevordering, netwerkactivering en onderzoek &amp; ontwikkeling. Beeld &amp; Geluid is de evenknie van EYE. Waar EYE zich richt op film, is Beeld &amp; Geluid als presentatieplek en archiefinstelling verantwoordelijk voor de televisiesector.</p>

<p>In de ondersteuningsstructuur in de meeste andere landen is internationale promotie ondergebracht bij het betreffende filmfonds. Soms is deze functie ook zelfstandig georganiseerd. In enkele gevallen zijn de functies van kennis, collectiebeheer, educatie, promotie en financiering gecombineerd. In de meeste landen of regio&rsquo;s zoals Vlaanderen is bovendien de filmsector gecombineerd met televisie en andere audiovisuele sectoren zoals interactive media en wordt integraal beleid gevoerd voor de audiovisuele sector, waar dat in Nederland niet het geval is. Volgens het Filmfonds is het een belangrijk punt van aandacht ook in Nederland integraal audiovisueel beleid te voeren.  </p>',
            	'sector_id' => '4'
            ],
            [
            	'title' => 'Creatieve Industrie',
            	'body' => '<p>Creatieve industrie is een wijdvertakte sector die veel disciplines bevat, waarbij er verschillende definities van de sector gehanteerd worden, zowel brede als meer beperktere definities. In de CBS Monitor Topsectoren ligt het accent op door de markt gefinancierde domeinen en minder op publiek gefinancierde domeinen zoals de culturele deelsectoren. De Monitor Creatieve Industrie van iMMovator kiest voor een nog bredere definitie waarin het accent ook op deze publiek gefinancierde domeinen ligt. Ook Cultuur in Beeld 2017 van het ministerie van OCW verwijst naar de definitie gehanteerd in deze monitor van iMMovator. In deze definitie behoren de deelsectoren Media- en Entertainmentindustrie (radio en televisie, persmedia, film, muziekindustrie, boekenindustrie, overige uitgeverijen, live entertainment), Creatieve Zakelijke Dienstverlening (vormgeving en ontwerp, Communiceren en informeren) en Kunsten en Cultureel Erfgoed (podiumkunsten, scheppende kunsten, overige kunst en erfgoed, cultureel erfgoed) tot de creatieve industrie. </p>

<p>In dit onderzoek wordt, net als in de eerder uitgevoerde sectorbeschrijving van de ontwerpende sectoren, echter aangesloten bij de scope van het cultuurbeleid van het ministerie van OCW, waarin architectuur, vormgeving, mode en digitale cultuur worden aangemerkt als creatieve industrie. In de landelijke rijksgefinancierde ondersteuning zijn er twee partijen binnen de sector Creatieve Industrie die ondersteuning bieden aan het brede veld van de creatieve industrie: het Stimuleringsfonds Creatieve Industrie (SCI) en Het Nieuwe Instituut. </p>

<p>Het SCI is het cultuurfonds voor architectuur, vormgeving, digitale cultuur en alle mogelijke crossovers daartussen. Het SCI is in 2013 voortgekomen uit het voormalige Stimuleringsfonds voor Architectuur. Het SCI kreeg een aantal taken overgeheveld van het Mondriaan Fonds op gebied van vormgeving. Ook kreeg het SCI er een aantal nieuwe taken bij, zoals het stimuleren van de e-cultuur dat tot dan toe nog nergens was belegd. De taak van het SCI hierbij is het ondersteunen van bijzondere en vernieuwende projecten en activiteiten van ontwerpers, makers en culturele instellingen in de creatieve industrie en het stimuleren van productie en presentatie van architectuur, vormgeving en digitale cultuur uit Nederland in binnenland &eacute;n buitenland. Via programma&rsquo;s en subsidies draagt het fonds bij aan het formuleren van ontwerpoplossingen voor maatschappelijke vraagstukken die breed gedragen zijn. </p>

<p>Het SCI heeft eind 2016 in totaal 23 medewerkers in dienst (20 fte) en een budget van 16 miljoen euro per jaar in de cultuurnotaperiode 2017-2020. Voor die beleidsperiode definieerde het fonds de volgende doelstellingen: bevorderen van talentontwikkeling en artistieke kwaliteit, stimuleren van onderzoek, analyse en reflectie, bevorderen van experimenten en crossovers, bevorderen van de professionalisering van de ontwerppraktijk en opdrachtgeverschap, bevorderen van maatschappelijk engagement en publieksactiviteiten en ten slotte het versterken van de internationale positie van de ontwerpsectoren. Omdat creatieve industrie ook sterk verbonden is met de sector economie, heeft specifiek het SCI niet alleen te maken met subsidie vanuit het ministerie van OCW. Het fonds heeft ook een subsidierelatie met de ministeries van Buitenlandse Zaken, waarvoor het diverse programma&rsquo;s uitvoert op het gebied van internationalisering en met het ministerie van Infrastructuur en Milieu op het gebied van architectuur en ruimtelijk ontwerp.</p>

<p>Het Nieuwe Instituut is ontstaan op 1 januari 2013 uit een fusie van het Nederlands Architectuurinstituut, Premsela, Nederlands Instituut voor Design en Mode en Virtueel Platform, kennisinstituut voor e-cultuur. Het Nieuwe Instituut opereert in het werkveld creatieve industrie vanuit het Rijksarchief voor de Nederlandse Architectuur en Stedenbouw, het museum voor Architectuur, Design en Digitale Cultuur en het agentschap voor Architectuur, Design en Digitale Cultuur. Het Nieuwe Instituut is hiermee een ondersteunende instelling met sectorale taken. Het Nieuwe Instituut probeert met haar activiteiten de wisselwerking tussen architectuur, vormgeving en digitale cultuur te versterken en aan de hand van actuele ontwikkelingen de betekenis van deze disciplines te verhogen. Research &amp; Development is hierin een verbindende factor. In 2016 waren er 90 mensen werkzaam bij Het Nieuwe Instituut.  </p>',
            	'sector_id' => '5'
            ],
            [
            	'title' => 'Letteren &amp; Bibliotheken',
            	'body' => '<p>De sector Letteren &amp; Bibliotheken kent verschillende invalshoeken, die we beknopt kunnen aanduiden als schrijven, lezen, kopen en lenen. De sector is veelvormig en bestaat uit zowel een publiek (gefinancierd) als een privaat deel. De letterensector is anders georganiseerd dan de meeste sectoren binnen cultuur. De financiering is dan ook anders, want niet de gehele keten (productie, distributie en exploitatie) is publiek gefinancierd. Dat heeft te maken met het feit dat de cultuurproducerende instellingen private partijen zijn. </p>

<p>In de ondersteuningsstructuur vervullen diverse instellingen ten aanzien van deze invalshoeken verschillende rollen. In dit onderzoek richten wij ons voornamelijk op het Letterenfonds, de Schrijverscentrale, Stichting Lezen en het Fonds Bijzondere Journalistieke Projecten, en die beschrijven wij hierna. Verder speelt de Koninklijke Bibliotheek (KB) een belangrijke rol in de ondersteuning en op veel andere vlakken, wat nadere toelichting behoeft. </p>

<p>Het Letterenfonds stimuleert, door middel van beurzen en subsidies aan schrijvers, vertalers, uitgevers en festivals, de kwaliteit en diversiteit in de literatuur en draagt bij aan de verspreiding en promotie van de Nederlands- en Friestalige literatuur in binnen- en buitenland. Het Letterenfonds ontvangt jaarlijks 10 miljoen euro subsidie van het ministerie van OCW en heeft 25 fte in dienst. </p>

<p>De Schrijverscentrale bemiddelt en adviseert bij het organiseren van auteurslezingen, zowel voor volwassenen als voor kinderen. De belangrijkste doelstelling is het bevorderen van een goede leescultuur, in het bijzonder het lezen van literatuur. De Schrijverscentrale speelt een rol in de verbinding tussen literatuur en het onderwijs, namelijk in het kader van culturele leesbevordering en leesplezier. </p>

<p>Stichting Lezen is het kennis- en expertisecentrum voor leesbevordering en literatuureducatie en maakt in die rol deel uit van de Basisinfrastructuur. De stichting zet zich in voor het verbeteren van het leesklimaat en de leescultuur, als onderdeel van het algemene lees- en literatuurbeleid van het ministerie van OCW.  Het Fonds Bijzondere Journalistieke Projecten (Fonds BJP) verleent financi&euml;le steun aan artikelen, reportages, longreads, journalistieke boeken en biografie&euml;n. Met kleinschalige subsidies beoogt het fonds journalisten in staat te stellen zich langdurig te verdiepen in een onderwerp of thema. Dit fonds is ontstaan uit een particulier initiatief en ontvangt sinds 1990 subsidie van het ministerie van OCW. Voor de periode 2017-2020 is dat 4 ton euro per jaar, net zoveel als in de voorgaande periode. </p>

<p>De KB is een wetenschappelijke instelling met een collectie van 7 miljoen items. De KB heeft een centrale en aansturende rol in het netwerk van openbare bibliotheken en heeft sinds het opgaan van drie organisaties in de KB in 2015 de rol en taken van het Sectorinstituut Openbare Bibliotheken overgenomen. De opdracht vanuit de Wsob laat zich onderverdelen in generieke en specifieke stelseltaken. Via de generieke taken (afstemming en co&ouml;rdinatie, educatie, reflectie en informatie, vertegenwoordiging en promotie) stuurt de KB het netwerk aan. Via de specifieke stelseltaken zorgt de KB voor instandhouding van de landelijke digitale bibliotheek, aangepast lezen, het collectieplan en gegevenslevering. De KB is in deze analyse meegenomen als ondersteunende instelling, maar heeft een andere status omdat deze instellingen niet vanuit de Basisinfrastructuur maar de Wsob is gefinancierd.</p>

<p>Een sectorinstituut voor de Letteren an sich heeft nooit bestaan. Het Sectorinstituut Bibliotheken (Siob) dat net was ontstaan werd in 2012 ontzien bij de bezuinigingen op cultuur onder Zijlstra. Het Siob is inmiddels samengegaan met de KB. De taken van de KB zijn voornamelijk gericht op het bibliotheekwezen. Het ontbreken van een sectorinstituut voor de Letteren betekent niet dat de ondersteunende taken niet voor een belangrijk deel worden vervuld. Dat gebeurt in de letterensector in gezamenlijkheid: het Letterenfonds en Stichting Lezen vervullen hierin een rol, deels in samenwerking met partijen als CPNB en producenten, en in verschillende samenwerkingsverbanden, zoals de KVB Adviesraad, KVB Boekwerk en de Leescoalitie. </p>

<p>Het Letterenfonds, de Schrijverscentrale en Stichting Lezen zijn in 2011 verhuisd naar een gezamenlijk Letterenhuis in Amsterdam met als doel meer onderlinge samenwerking te stimuleren. Het Fonds BJP heeft gezamenlijke huisvesting met instellingen uit de meer journalistieke hoek, zoals de Auteursbond en de Vereniging van Onderzoeksjournalisten (VVOJ). De capaciteit verschilt onderling sterk. Een instelling als het Fonds BJP heeft met 1,5 fte, buiten de subsidi&euml;ring van journalistieke projecten, weinig mogelijkheden om het veld anderszins te ondersteunen. De instellingen streven naar intensievere samenwerking om kwetsbaarheid te beperken en meer slagkracht te realiseren. </p>

<p>Om het lezen in Nederland te bevorderen hebben enkele landelijke organisaties, Stichting Lezen (voorzitter), Stichting Collectieve Propaganda van het Nederlandse Boek (CPNB), Stichting Lezen &amp; Schrijven, het Literatuurmuseum/Kinderboekenmuseum en de bibliotheken (KB en VOB), de krachten gebundeld in de Leescoalitie. Zij voeren activiteiten uit die erop zijn gericht om zoveel mogelijk mensen aan te zetten tot lezen en voorlezen. Ook is er het programma van drie ministeries van OCW, SZW en VWS: Tel mee met taal om het lezen en het plezier in lezen te bevorderen. Hiervan zijn onder meer de KB, de Stichting Lezen en de Stichting Lezen &amp; Schrijven partner. </p>',
            	'sector_id' => '6'
            ],
            [
            	'title' => 'Bovensectoraal Beleid',
            	'body' => '<p>Met het bovensectorale onderwerp Beleid doelen we op de ondersteuningsfuncties gekoppeld aan het cultuurbeleid van de overheid. Volgens de Wet en de Regeling op het Specifiek Cultuurbeleid is er subsidie geoormerkt voor &eacute;&eacute;n instelling met als kernactiviteit het verzamelen en verspreiden van kennis en informatie over kunst en cultuur in beleid en praktijk. De activiteiten van die instelling moeten gericht zijn op het bevorderen en faciliteren van onderzoek en van meningsvorming over de productie, distributie en afname van kunst en cultuur en over het nationale en internationale kunst- en cultuurbeleid. Hiervoor wordt in de regeling als aanduiding Onderzoek &amp; Statistiek gebruikt. </p>

<p>Bovensectoraal beleid is op basis van deze regeling door het ministerie van OCW belegd bij de Boekmanstichting, kenniscentrum voor kunst, cultuur en beleid in Nederland. Dit kenniscentrum heeft, volgens het Activiteitenplan 2017-2020, als primaire taak trends en ontwikkelingen in de culturele sector op onafhankelijke wijze en op basis van betrouwbare cultuurcijfers te duiden ten behoeve van de zichtbaarheid van cultuur in het maatschappelijke en politieke krachtenveld. Door zich hier optimaal voor in te zetten, komt de Boekmanstichting naar eigen zeggen tegemoet aan de behoefte van beleidmakers aan evidence-based cultuurbeleid &eacute;n draagt de stichting bij aan de professionalisering van het cultuurbeleid in Nederland.</p>

<p>De Boekmanstichting is er voor iedereen die zich vakmatig bezighoudt met cultuurbeleid, met een perspectief vanuit de culturele sector, overheid, media, wetenschap. De Boekmanstichting bedient daarmee de culturele sector van Kunst, Cultuur, Erfgoed en Creatieve industrie en in mindere mate Media en zoekt daarbij de raakvlakken met andere maatschappelijke domeinen op, te weten: sport, zorg en gezondheid, ruimtelijke ordening. De Boekmanstichting beschrijft in haar Activiteitenplan 2017-2020 vijf functies die grotendeels aansluiten op de in dit onderzoek onderscheiden ondersteuningsfuncties. De vijf functies en de relatie daarvan met de in dit onderzoek benoemde functies zijn de volgende: </p>
<ul>
<li><em>Duiding</em> (vergelijkbaar met informatievoorziening): de Boekmanstichting geeft betekenis aan kwantitatieve en kwalitatieve gegevens. Het betreft dataverzameling, beleidsinformatieverzameling, analyse, verklaring en ontsluiting. Met uitvoering van deze functie zet de stichting haar kennis en kunde in voor het duiden van maatschappelijke en sociale trends in het veld van cultuurbeleid. </li>

<li><em>Debat</em> (komt terug in netwerkactivering): de Boekmanstichting jaagt op een onafhankelijke, neutrale wijze het culturele debat aan. De debatfunctie heeft tot doel meningsvorming te bevorderen; de Boekmanstichting biedt een platform voor alle standpunten die er zijn en ontfermt zich over het agenderen van onderwerpen die in ieders belang zijn, maar waarvan niemand zich eigenaar voelt. </li>

<li><em>Documentatie</em> (komt terug in beheer &amp; ontsluiting en informatievoorziening): dit betreft de (digitale) bibliotheek, catalogus, archief, kennisborging, (data)informatieontsluiting en collectiebeheer.</li>

<li><em>Deling</em> (vergelijkbaar met netwerkactivering): deze functie uit zich in het optreden als verbinder. (Onverwachte) partijen die elkaars kennis (en bereik) kunnen gebruiken en elkaar kunnen versterken en inspireren, vinden elkaar via de Boekmanstichting. Op die manier draagt de stichting haar platformfunctie uit.</li>

<li><em>Diensten</em> (met lage prioriteit en deze functie komt alleen terug in de vorm van opdrachttaken onder beleidsondersteuning): hieronder verstaat de Boekmanstichting het uitvoeren van werkzaamheden, zoals het doen van onderzoek en het inhoudelijk vormgeven van evenementen, debatten en congressen, voor een opdrachtgever tegen vergoeding. </li>
</ul>
<p>De Boekmanstichting is met 8 fte klein qua omvang, niet alleen in vergelijking met bijvoorbeeld het LKCA als bovensectoraal kennisinstituut voor cultuureducatie en cultuurparticipatie, maar ook in vergelijking met de rijksgefinancierde kennisinstituten in andere maatschappelijke sectoren, zoals is gebleken in het onderzoek De publieke kennisorganisaties van het Rathenau Instituut uit 2016. De Boekmanstichting is ruimschoots de kleinste van de 29 vergeleken (maar sterk verschillende) kennisorganisaties. Daarna komt Geonovum (geo-informatie, door I&amp;M gefinancierd) met 13,4 fte en het Mulier Instituut (sport, door VWS gefinancierd) met 19 fte. De Boekmanstichting kent evenwel veel activiteiten en een divers palet aan ingezette middelen en uitingen op de verschillende functies. De Boekmanstichting heeft slechts beperkte capaciteit in relatie tot de ambitie van het bieden van ondersteuning aan de cultuursector over de volle breedte.</p>',
            	'sector_id' => '7'
            ],
            [
            	'title' => 'Bovensectoraal Digitalisering',
            	'body' => '<p>Digitalisering is een onderwerp dat al lange tijd beleidsaandacht vraagt. De landelijke ondersteuning op het gebied van digitalisering ligt bij Digitaal Erfgoed Nederland (DEN), het kennisinstituut van de digitale cultuur. DEN is in 1996 gestart als publieksorganisatie door een groep erfgoedinstellingen om samenwerking op het gebied van ICT te stimuleren. Toen de kwaliteitszorg op dit gebied ook belegd werd bij DEN, is DEN in 2005 overgegaan van een vereniging naar een stichting, om de onafhankelijkheidspositie te kunnen waarborgen. DEN ondersteunt erfgoedbeherende instellingen, en sinds januari 2017 ook cultuurproducerende instellingen, waaronder in de podiumkunsten.</p>

<p>DEN wil, in gezamenlijkheid met cultuurproducerende en erfgoedbeherende instellingen, een actieve bijdrage leveren aan de informatiemaatschappij. DEN bevordert en bewaakt de kwaliteit van digitale dienstverlening en digitalisering, investeert in de kennisontwikkeling, stimuleert de instellingen om te innoveren en aan de eisen van de digitale samenleving te voldoen, versterkt de toekomstvastigheid en publieksgerichtheid van de nationale infrastructuur voor digitaal erfgoed en bewaakt de aansluiting van de Digitale Collectie Nederland op andere nationale en internationale diensten en voorzieningen. </p>

<p>In 2011 is het een voornemen geweest om DEN na de beleidsperiode van 2013-2016 niet meer te financieren vanuit de overheid. Het ministerie van OCW heeft erkend dat DEN een probleem adresseert dat zonder DEN niet voldoende geadresseerd zou worden, en dat de instellingen in het culturele veld nog steeds behoefte hebben aan ondersteuning op het gebied van digitalisering. Zodoende heeft DEN vanaf 2017 opnieuw een plek gekregen in de basisinfrastructuur. Via (Europese) projectgelden kon DEN de afgelopen jaren de formatie tijdelijk uitbreiden. Vanwege de nieuwe invulling van taken en prioriteiten per 2017 is het een bewuste keuze geweest van DEN om te focussen op de kerntaken en aanpalende projectactiviteiten (tijdelijk) te verminderen. </p>

<p>Er zijn andere partijen die zich op hetzelfde terrein begeven als DEN, zoals Beeld &amp; Geluid en EYE voor film en beeld, LIMA specifiek voor de mediakunst, de Rijksdienst voor Cultureel Erfgoed (RCE) en het RKD richting musea en beeldende kunst, Het Nieuwe Instituut voor de creatieve industrie, de Koninklijke Bibliotheek (KB) en het Nationaal Archief voor bibliotheken en archieven, en op erfgoedniveau ook de provincies. Echter, er zijn geen andere instellingen die zoals DEN de kennis omtrent digitalisering landelijk verknopen over de sectoren heen. Er is wel het Netwerk Digitaal Erfgoed (NDE), dat als doel heeft landelijke voorzieningen en diensten te ontwikkelingen voor het verbeteren van de zichtbaarheid, de bruikbaarheid en de houdbaarheid van digitaal erfgoed. Op Europees gebied speelt Europeana een rol in het vergroten van de bovensectorale samenwerking. </p>

<p>Een aandachtspunt volgens DEN is de kwetsbaarheid van de eigen organisatie. De organisatie is klein, met 5,7 fte in dienst en de kennis en het netwerk van de directie zijn cruciaal voor het succes. Ter vergelijking: in de onderwijssector is Kennisnet actief in de ondersteuning van onderwijsinstellingen op het gebied van ICT en heeft 96 fte in dienst. De vergelijking gaat niet volledig op omdat het primair en het voortgezet onderwijs in de uitvoering van primaire processen meer afhankelijk zijn van Kennisnet omtrent de ICT dan de cultuursector dat is van DEN.  </p>',
            	'sector_id' => '8'
            ],
            [
            	'title' => 'Bovensectoraal Ondernemerschap',
            	'body' => '<p>Cultureel ondernemerschap is al in zwang in het cultuurbeleid sinds staatssecretaris Van der Ploeg in de periode 1998-2002. Hij beschreef cultureel ondernemerschap als een &ldquo;houding die erop is gericht zoveel mogelijk kunstzinnig, artistiek-cultureel, zakelijk en maatschappelijk rendement te halen uit culturele voorzieningen.&rdquo; Sindsdien heeft cultureel ondernemerschap een belangrijke plaats gekregen in het cultuurbeleid van het rijk, en evenzeer van provincies en gemeenten. Onder staatssecretaris Zijlstra lag de focus op het vergroten van eigen inkomsten, gelijktijdig met verlaging van de subsidies voor kunst en cultuur. Cultureel ondernemerschap is daarmee een belangrijk strategisch en bedrijfsmatig onderwerp voor vrijwel alle culturele instellingen, of zij nu wel of niet subsidie ontvangen, en dat geldt ook voor individuele kunstenaars in hun eigen beroepspraktijk. </p>

<p>Om de cultuursector te ondersteunen bij het vormgeven en versterken van ondernemerschap heeft het ministerie van OCW in 2013 het programma Ondernemerschap Cultuur ge&iuml;nitieerd, dat liep tot en met 2017 en daarna niet wordt vervolgd. Doel van het programma was om het ondernemerschap in de culturele sector te vergroten, onder andere door het verbreden van de financieringsmix, waardoor de sector meer eigen inkomsten zou gaan verwerven. Het programma startte in een periode van economische recessie en bezuinigingen op cultuur, waardoor overheid en sector de focus op ondernemerschap als zeer urgent voelden. Het programma bestond uit vier onderdelen:  </p>

<ul>
<li>Activiteiten voor kleine en middelgrote culturele instellingen en individuele kunstenaars en creatieve makers, uitgevoerd door Cultuur+Ondernemen</li>

<li>Het opleidingsprogramma <em>Leiderschap in Cultuur</em> (LinC), uitgevoerd door de Universiteit Utrecht en Kennisland in samenwerking met de HKU en Coaching in de Cultuur</li>

<li><em>Wijzer Werven</em>, training en coaching van culturele ANBI&rsquo;s op het gebied van financieringsmix en fondsenwerving, uitgevoerd door Van Dooren Advies en Charistar in samenwerking met Berenschot, en </li>

<li>De campagne <em>Cultuur, daar geef je om</em>, uitgevoerd door het ministerie van OCW zelf.  </li>
</ul>

<p>Naast de hierboven genoemde uitvoerders van het programma Ondernemerschap Cultuur zijn er veel andere partijen die het ondernemerschap in de cultuursector ondersteunen. Voorbeelden zijn provinciale steunfuncties, zoals bkkc in Noord-Brabant, provinciale cultuurfondsen zoals Cultuurfonds Gelderland, grote culturele instellingen die hun collega&rsquo;s helpen, brancheorganisaties, onderwijsinstellingen en commerci&euml;le onderzoeks- en adviesbureaus.</p>

<p>In dit onderzoek gaat de aandacht uit naar de ondersteuning op het gebied van ondernemerschap door Cultuur+Ondernemen (C+O), het kenniscentrum voor ondernemerschap in de cultuursector. C+O is tot stand gekomen in 2010 door een fusie van Kunstenaars&amp;Co, dat zich richtte op individuele kunstenaars, en Kunst &amp; Zaken, dat was gericht op culturele instellingen en het bedrijfsleven. Tot de afschaffing van de Wet Werk en Inkomen Kunstenaars (WWIK) in 2012 ontving C+O in het kader van de uitvoering van de WWIK ten eerste subsidie van het ministerie van SZW voor het doen van beroepsmatigheidstoetsen, ten tweede subsidie van het ministerie van OCW ten behoeve van de wettelijke taak, namelijk de uitvoering van het flankerend beleid langszij de WWIK en ten derde subsidie van het ministerie van OCW voor de taken die door het toenmalige Kunst &amp; Zaken werden uitgevoerd. In het verleden zijn diverse programma&rsquo;s bij C+O en zijn voorgangers ondergebracht door het ministerie van OCW, waaronder de ontwikkeling van de Governance Code Cultuur en het programma Cultuurmecenaat. </p>

<p>C+O ontvangt, in tegenstelling tot andere bovensectorale ondersteunende instellingen, geen instellingssubsidie van het ministerie van OCW vanuit de Basisinfrastructuur, maar projectsubsidie. Bij het instellen van het programma Ondernemerschap Cultuur door het ministerie van OCW werden in 2014 de activiteiten die C+O aan kleine en middelgrote culturele instellingen en individuele kunstenaars en creatieve makers aanbiedt ter versterking van hun ondernemerschap ondergebracht in dit programma. Het programma liep eind 2017 af. Het ministerie van OCW stelt wel aan C+O projectsubsidie beschikbaar voor de jaren 2017-2018 voor de ondersteunende functie voor ondernemerschap. Nog onbekend is of deze functie na 2018 zal blijven bestaan en, zo ja, in welke vorm. Naast de projectsubsidie realiseert C+O inkomsten uit publieke (onder andere sociale fondsen) en private bronnen (fondsen en opdrachtgevers). C+O had eind 2016 20,8 fte in dienst. </p>

<p>De doelgroepen van C+O zijn culturele organisaties (vooral klein en middelgroot, in principe niet de Basisinfrastructuur-instellingen), zelfstandig werkende kunstenaars en zogenaamde creatieven. C+O ondersteunt deze spelers bij professionalisering, bij het vinden van passende financiering, bij het vinden van nieuwe businessmodellen en bij het up to date houden en/of optimaliseren van de governance. C+O verricht de volgende activiteiten, die mede worden gefinancierd vanuit de projectsubsidie die C+O ontvangt in het kader van het programma Ondernemerschap Cultuur, maar ook andere financiering kennen: </p>

<ul>
<li>Startadviezen aan instellingen, creatieve ondernemingen, individuele kunstenaars en creatieven, evenwichtig verdeeld over de verschillende doelgroepen, disciplines en regio&rsquo;s. Een gratis startadvies kan aanleiding geven voor een intern of extern betaald adviestraject. </li>

<li>Advies en begeleiding bij het opzetten en vernieuwen van financi&euml;le diensten. Het doel hiervan is om de financieringsmogelijkheden en -diversiteit te vergroten (nieuwe verdienmodellen en daarop afgestemde financieringsmix) en zo meer cultuurproductie en -distributie mogelijk te maken. C+O zet instrumenten in als cultuurleningen, microkredieten en garantstellingen</li>

<li>Advies en ondersteuning aan besturen en raden van toezicht bij het toepassen van de Governance Code Cultuur. In 2017 is een herziening van de Code voorzien. </li>

<li>Onderzoek naar kansen, voorwaarden en bruikbaarheid van nieuwe financieringsmodellen in de cultuursector en deling van kennis/inzichten uit onderzoek met de sector. </li>
</ul>
',
            	'sector_id' => '9'
            ],
            [
            	'title' => 'Bovensectoraal Internationalisering',
            	'body' => '<p>Het onderwerp internationalisering is een taak van de sectorale fondsen, maar is ook expliciet bovensectoraal belegd bij DutchCulture, centrum voor internationalisering. DutchCulture is er voor culturele professionals en diplomaten, overheden (nationaal, regionaal, stedelijk en de Europese Unie). Verder richt het zich op fondsen, instituten en overige partijen in het onderwijs, pers &amp; media, het internationale veld en publiek. Kortom, iedereen die zich op een bepaalde manier bezighoudt met internationalisering van cultuur. Doel van DutchCulture is internationale samenwerking in kunst, cultuur en erfgoed te steunen en stimuleren. </p>

<p>De ministeries van OCW en Buitenlandse Zaken hebben in het Beleidskader Internationaal Cultuurbeleid 2017-2020 voor DutchCulture een aantal focuslanden benoemd voor de beleidsperiode 2017-2020. Dat zijn Belgi&euml;/Vlaanderen, China, Duitsland, Frankrijk, Indonesi&euml;, Turkije, de Verenigde Staten en het Verenigd Koninkrijk.</p>

<p>DutchCulture is een fusieorganisatie van SICA, Trans Artists and MEDIA Desk Netherlands en is in deze hoedanigheid actief sinds 2013. Onderdeel van DutchCulture is Creative Europe Desk, voor informatie en advies over financiering in Europese context. DutchCulture heeft 37 medewerkers (ruim 23 fte) in dienst. DutchCulture voert een aantal bovensectorale functies zelf uit en kan doorverwijzen naar meer sectorspecifieke ondersteunende partijen. </p>',
            	'sector_id' => '10'
            ],
            [
            	'title' => 'Bovensectoraal Cultuureducatie &amp; Cultuurparticipatie',
            	'body' => '<p>Cultuureducatie en cultuurparticipatie vormen bovensectoraal onderwerpen, maar wijken af van de andere bovensectorale onderwerpen doordat het veld er op een andere manier mee bezig is. Cultuureducatie is een primaire taak van een aantal cultuureducatieve instellingen en het is een belangrijke secundaire taak van cultuurproducerende instellingen. Verder bestaat een aanzienlijk deel van cultuurparticipatie uit de beoefening van amateurkunst, door individuen (volgens de Monitor Amateurkunst 2017 van het LKCA 40% van de Nederlandse bevolking vanaf 6 jaar) en door een zeer omvangrijk en divers geheel van verenigingen en andere instellingen. Dat maakt dat cultuureducatie en cultuurparticipatie, naast dat het bovensectorale onderwerpen in de ondersteuningsstructuur zijn, ook sectoren op zich vormen die alle culturele disciplines omvatten.</p>

<p>Op rijksniveau zijn er twee instellingen bij wie de ondersteuning voor deze bovensectorale onderwerpen is belegd, namelijk het Landelijk Kennisinstituut Cultuureducatie en Amateurkunst (in de rest van dit rapport aangeduid als het LKCA) en het Fonds voor Cultuurparticipatie (FCP). </p>

<p>Het LKCA staat voor de waarden van cultuureducatie en actieve cultuurparticipatie en draagt deze actief uit. Het LKCA wil ervoor zorgen dat iedereen op school en in de vrije tijd goede cultuureducatie krijgt en dat cultuurparticipatie voor iedereen mogelijk is. Het kennisinstituut LKCA is in 2012 voortgekomen uit een fusie van Kunstfactor, dat zich richtte op amateurkunst, en Cultuurnetwerk, kenniscentrum voor cultuureducatie. Het LKCA richt zich op professionals die werken voor cultuur op school of in de vrije tijd. Het LKCA had eind 2016 een formatie van 52 fte. </p>

<p>Het FCP financiert sinds 2009 instellingen en initiatieven in de vorm van regelingen en stimuleringsprogramma&rsquo;s op het gebied van cultuureducatie en cultuurparticipatie en heeft in het verlengde daarvan enkele ondersteunende werkzaamheden. Het FCP ondersteunt en verbindt mensen, organisaties en overheden die werk maken van cultuurparticipatie. De drie programma&rsquo;s zijn Cultuureducatie met Kwaliteit, Innovatie in Cultuur-maak het mee en Cultuur maakt iedereen zichtbaar. Het FCP heeft een jaarlijkse begroting van 25 miljoen euro, waarvan 22,5 miljoen euro via programma&rsquo;s wordt besteed aan financiering en subsidi&euml;ring van het veld. Het FCP had eind 2016 een formatie van 30 medewerkers, bijna 25 fte. </p>

<p>In de aanloop naar de beleidsperiode 2017-2020 hebben het FCP en het LKCA een gezamenlijke ambitie geformuleerd. Zij trekken samen op, ieder vanuit zijn eigen onafhankelijke rol, om nieuwe ontwikkelingen te signaleren, agenderen en stimuleren in de werkvelden cultuureducatie en cultuurparticipatie. Zij doen dit door het delen van praktijkervaringen, het verbinden van netwerken en het ondersteunen van innovatieve en inspirerende projecten gericht op onderwijs, samenleving, infrastructuur en waardering. Het FCP stimuleert daarbij ontwikkeling, zichtbaarheid en verbinding van cultuureducatie en cultuurparticipatie via subsidieregelingen en activiteiten, gericht op de doelgroepen die het FCP ondersteunt. Het LKCA stimuleert ontwikkeling door ontmoeting en debat en door te voorzien in kennis en kaders. Het LKCA houdt daarbij een spiegel voor door goede voorbeelden en het bieden van inzicht in relevante ontwikkelingen op (inter)nationaal gebied. </p>

<p>Voor de branche met aanbieders van cultuureducatie en cultuurparticipatie zelf, dus instellingen zoals kunstencentra en verenigingen zijn talloze koepels, brancheorganisaties, vakverenigingen, bonden en vakbonden actief in ondersteuning. De voornaamste speler in de branche van cultuureducatie is Cultuurconnectie. Ook voor de ondersteuning van het onderwijs op het gebied van cultuureducatie zijn diverse organisaties in meer of mindere mate actief, zoals de Vereniging Onderwijs Kunst &amp; Cultuur (Vonkc), Algemene Vereniging Schoolleiders (AVS), Vereniging van Cultuurprofielscholen (VCPS), nationaal expertisecentrum leerontwikkeling SLO en dergelijke. Bij de beleidsvorming op het gebied van cultuureducatie en cultuurparticipatie zijn overheden betrokken en ondersteunen elkaar, deels ook via verbanden als de VNG en het IPO. </p>

<p>Op het gebied van cultuureducatie zijn veel regionale en lokale ondersteunende instellingen actief. Dit doen zij in verschillende rollen en functies, soms op meer beleidsmatige en inhoudelijke terreinen zoals kennis, informatie en deskundigheid, soms meer praktisch als intermediair tussen scholen, culturele instellingen en verenigingen en zelfstandige professionals. Het samenspel met deze instellingen is verbeterd, maar soms staan activiteiten nog op gespannen voet, zo merken spelers in het geraadpleegde veld op. Het LKCA richt zich op landelijke activiteiten en beperkt zich in lokale activiteiten, om zo voorkomen dat overlap ontstaat met wat regionale en lokale ondersteunende partijen (kunnen) doen. Daarbij helpt het dat het LKCA het landelijke geheel overziet, waar deze organisaties een kleiner gebied bestrijken.</p>

<p>Het LKCA richt zich niet op individuen die les krijgen of kunst beoefenen, maar op de professionals in cultuureducatie en cultuurparticipatie. De professionele partijen die het meest bezig zijn met cultuureducatie behoren tot de culturele sector en het onderwijs. Naast de instellingen is een groot en groeiend aantal zzp&rsquo;ers actief in de cultuureducatie en cultuurparticipatie, waar het LKCA zich ook op richt. Vanwege de verbindingen met andere domeinen zoals het sociaal domein, zorg en welzijn, sport, openbare ruimte en community arts (sociaal-maatschappelijke vraagstukken) richt het LKCA zich ook op professionals die buiten de culturele sector en het onderwijs werkzaam zijn, zoals professionals in zorg en welzijn die zich bezig houden met de inzet van kunst en cultuur in die sectoren. Dat maakt het werkveld van het LKCA zeer breed en divers. </p>',
            	'sector_id' => '11'
            ],
        ];

        DB::table('toelichtingsectors')->insert($toelichtingsectors);
    }
}



